### ISSUE TITLE
Adminlte to be link in joomla

### ISSUE THREAD

**Issue by jaasaria** [almasaeed2010/AdminLTE#1000]
Hi guys, currently im working with joomla(cms) and like to use this template for my dashboard data. Could somebody give me an idea or tutorial how to accomplish this thing? I think this is a good,easy and awesome way for website development. Feel free to share your idea. Thanks

**Comment by lenamtl** [comment]
This will required a lot of work, Joomla template is complicated.

**Comment by jaasaria** [comment]
Okay ill look for any possible option. anyways thanks for the reply. Appreciated!

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
