### ISSUE TITLE
Keep class "active" after close Multilevel menu in Left Sidebar

### ISSUE THREAD

**Issue by Onfealive** [almasaeed2010/AdminLTE#1002]
![before](https://cloud.githubusercontent.com/assets/18258131/14242572/523c546a-fa7b-11e5-9e08-f854baf4ca29.jpg)![working](https://cloud.githubusercontent.com/assets/18258131/14242571/523bf22c-fa7b-11e5-84c8-950d55506e03.jpg)![after](https://cloud.githubusercontent.com/assets/18258131/14242573/5247b06c-fa7b-11e5-9d6e-6e835225dd37.jpg)

Thanks!

**Comment by AEK-BKF** [comment]
:+1:  we need it :)

**Comment by wmarques** [comment]
If one of you have a fix for this, it's an annoying bug :(

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
