### ISSUE TITLE
Floating panel

### ISSUE THREAD

**Issue by chris-rs** [almasaeed2010/AdminLTE#1004]
Hi,

I like to create a floating panel right aligned in the browser window which I can collapse and expand. When it's collapsed the panel header remains visible so I can toggle the appearance.
The template has a nice chat layout but I do not want it in the grid but floating above it (use it like the control-sidebar feature). Users can easily scroll the page and chat at the same time. They can collapse the chat panel when they don't need it at the moment. The still visible header could display a notification when new messages are there, so the user can expand when he like to proceed chatting.
After some googling, it seems to be a unique feature for bootstrap and this template. It requires a different panel layout (with vertical headerbar) and horizontal collapsing.

Hope someone can help me with the necessary CSS/Javascript.

Regards,

Chris

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
