### ISSUE TITLE
input-group-addon doesn't consider has-error

### ISSUE THREAD

**Issue by luposky** [almasaeed2010/AdminLTE#1008]
I have a simple bootstrap input field like this (with an icon on the right using input-group-addon) :

`<div class="form-group">
                <div class="input-group">
                    <input type="email" class="form-control" placeholder="Email" >
                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span> 
                </div>
</div>`

The input-group-addon background is always white, independently from the field status has-error or has-warning, overriding the default bootstrap behavior when using validators like formvalidation.io

Actual result with fields validated (input-group-addon of the email field have a white background):
![immagine1](https://cloud.githubusercontent.com/assets/1070180/14408703/f29b93e8-feff-11e5-941e-303363a07fcd.png)

Desidered result (disabling the two rules of adminlte):
![immagine2](https://cloud.githubusercontent.com/assets/1070180/14408704/f68720bc-feff-11e5-9648-67510dfc45ac.png)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
