### ISSUE TITLE
Active submenu item after reopening tree

### ISSUE THREAD

**Issue by adminko-svk** [almasaeed2010/AdminLTE#1009]
Hello!
When you open the page "Dashboard" https://almsaeedstudio.com/preview and you click on "Dashboard" in left menu, the submenu tree close.
When you click on this closed submenu again, the "Dashboard v2" item is not active (the font color is not white).

Is this normal?!
Can you fix it in next release please?

![fix](https://cloud.githubusercontent.com/assets/11200226/14421171/659a0f8e-ffd0-11e5-9ae1-6d41131dfbca.jpg)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
