### ISSUE TITLE
Can i expand sidebar menu to scroll down from navbar in mobile size? 

### ISSUE THREAD

**Issue by hfishere** [almasaeed2010/AdminLTE#1011]
First, forgive me if you not understand my question title..

This what i mean, ill explain in picture, hope you understand it:

![admlte](https://cloud.githubusercontent.com/assets/13634344/14482493/673e40e2-0167-11e6-9bd2-3d5f8f3af82e.png)

In picture above, the sidebar is shown from left to right in mobile size.. But i want to make it scroll down from navbar like this:

![sbadmin](https://cloud.githubusercontent.com/assets/13634344/14482584/7a6ac216-0168-11e6-8b15-f616b5f13739.png)
Is my purpose be possible?

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
