### ISSUE TITLE
When Box is Shown

### ISSUE THREAD

**Issue by LeonSutedja** [almasaeed2010/AdminLTE#1014]
I have a fullcalendar inside a box.

The problem is that, the initial state of the box is at a collapsed box when the page loaded.
FullCalendar won't work when the div is hidden, and will not render.

In this case, I have to attach the fullCalendar initialization for when the slideDown is finish, but currently we don't have any extension to do this.

Any advise or if anyone had done something similar like this before is appreciated.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
