### ISSUE TITLE
Question about menu on sidebar collapse

### ISSUE THREAD

**Issue by FireFoxII** [almasaeed2010/AdminLTE#1021]
Hi and sorry for my english...

It's possible, when sidebar is collapsed, to get multilevel menu that show always next level on right side (then horizontal) on mouse over instead of dropdown when click?

**Comment by FireFoxII** [comment]
Nothing? Not possibile?

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
