### ISSUE TITLE
How I get the left Navigation to expand collapse on mobile view

### ISSUE THREAD

**Issue by RamiroVidal** [almasaeed2010/AdminLTE#1023]
Hi:
Excuse my ignorance, but I am trying to create a different button to expand and collapse the left navigation. It works on full screen but not mobile screens. On mobile it does not do anything.. :(

CODE
function toggle_sidebar(){
	$("[data-toggle='offcanvas']").click();
}

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
