### ISSUE TITLE
Display Problems

### ISSUE THREAD

**Issue by MH34** [almasaeed2010/AdminLTE#1026]
(Sorry for my bad english)

hello

When I use scripts coded in ANSI I have no worries : the display conforms to the template.
But if I UTF8 code ( because it is a French site and I need accents ) then there is a space below the top navigation bar and above the footer (see the file attached).
Does anyone know why ?
Thank you in advance

![screen](https://cloud.githubusercontent.com/assets/7139523/14913090/bc18eb26-0e00-11e6-927c-7b28709c4990.jpg)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
