### ISSUE TITLE
content-wrapper not obeying height changes for bootstrap

### ISSUE THREAD

**Issue by Rumple-Phillip** [almasaeed2010/AdminLTE#1027]
Hello, we are using this wonderful template for our CRM, but we have run into a situation where when bootstrap changes the size layout of the screen from lg -> md -> sm -> xs, the content-wrapper isn't properly adjusting the height: 
![firefox_2016-04-29_09-02-26](https://cloud.githubusercontent.com/assets/6059253/14921955/be5e15f8-0de9-11e6-83ac-f685c07edff8.png)

As you can see, when boostrap resized the screen, the content wrapper didn't maintain full height, thus causing the background not to be around the content.  This is quite frustrating, and I'm not 100% sure how to fix that.

**Comment by rquishpe** [comment]
There is a fix to this issue?

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
