### ISSUE TITLE
Bug with sidebar collapse and multilevel menu ?

### ISSUE THREAD

**Issue by FireFoxII** [almasaeed2010/AdminLTE#1028]
When sidebar is collapsed and click on multilevel menu to dropdown, next click will not close the dropdown

![problem](https://cloud.githubusercontent.com/assets/4954095/14935125/ff754844-0ec6-11e6-8d07-14bfbaeb9686.png)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
