### ISSUE TITLE
Feature request: Add support for light text on dark background themes.

### ISSUE THREAD

**Issue by tioteath** [almasaeed2010/AdminLTE#1030]
White background is not good for light emitting screens. Dark background causes much less eyestrain (CO). It would be nice to have a theme without white backgrounds (especially for graphs).

**Comment by Metehan** [comment]
+1

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
