### ISSUE TITLE
other library not working

### ISSUE THREAD

**Issue by cdmathukiya** [almasaeed2010/AdminLTE#1031]
i am using this admin panel. but all functionality of select2 is not working and i am include another library jquery.bbq and try to use it's function but not working and occurs error that function not define. 
i think in this external library not working, please help to solve this issue.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
