### ISSUE TITLE
control-sidebar overflow issue

### ISSUE THREAD

**Issue by SplicePHP** [almasaeed2010/AdminLTE#1032]
If you change the tab in the control-sidebar and the content exceeds the height of the page you are unable to scroll down to view the rest of the content in the sidebar and it simply remains hidden.
This is how you can fix it:
```
$('.control-sidebar a[data-toggle="tab"]').on('shown.bs.tab', function () {
    $.AdminLTE.layout.fix();
});
```

**Comment by Taewa** [comment]
@SplicePHP Thank you very much!

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
