### ISSUE TITLE
Adminlte issue with ASP tags

### ISSUE THREAD

**Issue by sujit223** [almasaeed2010/AdminLTE#1035]
Hi Almasaeed Team,

**You guys rocxzz,**
Just recently found an issue with Adminlte and laravel.
In Adminlte theme there are some ASP tags used in this link view-source:https://almsaeedstudio.com/themes/AdminLTE/pages/charts/chartjs.html search for the term "**<%**" this tags causes problem for some servers while working with laravel. 
You can find one issue logged here too https://github.com/ladybirdweb/faveo-helpdesk/issues/7.
We need to disable asp tags on the server of people using the system manually.
Can you please look into the issue if it is possible to fix it.

Thank You.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
