### ISSUE TITLE
Ionicons, Font Awesome, etc.

### ISSUE THREAD

**Issue by NLeone** [almasaeed2010/AdminLTE#1036]
Hello! I am translating with google, sorry if something is not well understood.

I want to know if you can download files locally that are linked remotely, such as ionicons, font-awesome, etc.

Because if you stop working at some point by an external problem, our projects stop visuarlizarse correctly.

I hope someone can help with this query.

Regards!

**Comment by shaneyboi** [comment]
I believe you can download ionicons via github (http://ionicons.com) as well as font-awesome via github (https://fortawesome.github.io/Font-Awesome/). If this is what you are asking?

**Comment by NLeone** [comment]
Shaneyboi Hello!

Yes, that's what I'm asking, but you know, I've done, but I do not download it clear that I locate folder for the template code take it.

I've tried and I can not impacting the template .....

Someone has done?

Thank you very much and greetings!

**Comment by Pyreweb** [comment]
The template makes references to the ionicons and font-awesome in the ``<head>``
```
<!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
```
Just replace theses references with your local files path

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
