### ISSUE TITLE
Datatables inside AdminLTE problem

### ISSUE THREAD

**Issue by alexbible** [almasaeed2010/AdminLTE#1038]
Dear AdminLTE & friends,

I am creating a Bible with datatables. Searching feature works for me here:
http://torah.byethost14.com/crud/____en_define_table_layout_min.html

But it does not work for me inside the AdminLTE here:
http://torah.byethost14.com/crud/_index2_start_again.html

I have tried loading the scripts before the < / head >
I also tried before the < / body >

What am I missing?

**Comment by suvjunmd** [comment]
Hey @alexbible,

replace the line:
```javascript
var table = $('table.table').DataTable( {
```

with:
```javascript
var table = $('#talmidimEdition').DataTable( {
```

**Comment by alexbible** [comment]
thank you Dimitri :)
Here's my progress: http://torah.byethost14.com/crud/pages/tables/_data.html
I really appreciate it,
Alex

**Comment by kressly** [comment]
@alexible I like ur bible project. What problem are u facing now after the progress. I would like to help u.

**Comment by alexbible** [comment]
Good morning @kressly . Our Abba in heaven is always with us and puts us together :) I'm glad to meet you! Here's my contact info: smuglovsky@gmail.com // skype id: "smuglovsky" // and here's my work page: www.facebook.com/granjasolidaria (it's in Spanish but you'll enjoy the pictures). I'm normally back from the villages at 9 pm (Ghana time)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
