### ISSUE TITLE
phpStorm is throwing me errors on the AdminLTE..css

### ISSUE THREAD

**Issue by InsiteFX** [almasaeed2010/AdminLTE#1039]
phpStorm is throwing me errors on the AdminLTE..css:

.small-box h3,
.small-box p {
  z-index: 5px; <-- Error! <------------------------
}

All Gradients are throwing errors on this -moz-linear-gradient :
.bg-green-gradient {
  background: #00a65a !important;
  background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #00a65a), color-stop(1, #00ca6d)) !important;
  background: -ms-linear-gradient(bottom, #00a65a, #00ca6d) !important;

  background: -moz-linear-gradient(center bottom, #00a65a 0%, #00ca6d 100%) !important; <-- Error! <----------------------

  background: -o-linear-gradient(#00ca6d, #00a65a) !important;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00ca6d', endColorstr='#00a65a', GradientType=0) !important;
  color: #fff;
}

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
