### ISSUE TITLE
Problem with the collapsed sidebar

### ISSUE THREAD

**Issue by Sreejithw** [almasaeed2010/AdminLTE#1045]
Hi, 

I'm currently having some issues with the sidebar-collapse feature. I'm currently trying to hide the sidebar and the toggle button in desktop view and only make them appear in mobile view . It is collapsing but when I toggle the sidebar in mobile view and switching back to desktop view ,the sidebar is re-appearing.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
