### ISSUE TITLE
select2 form add-on causes rogue arrow to appear

### ISSUE THREAD

**Issue by owalerys** [almasaeed2010/AdminLTE#1048]
Prepending an add-on to the select2 object causes a rogue arrow to appear

```
    <div class="box-body">
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <label>Allocation</label>
                    <select class="form-control select2" style="width: 100%;">
                        <option>Option 1</option>
                        <option>Option 2</option>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i> Allocation</span>
                    <select class="form-control select2" style="width: 100%;">
                        <option>Option 1</option>
                        <option>Option 2</option>
                    </select>
                </div>
            </div>
        </div>
    </div><!-- /.box-body -->
```

![image](https://cloud.githubusercontent.com/assets/8883074/15191843/837b457e-1784-11e6-9d28-fe4247cc146b.png)

**Comment by owalerys** [comment]
It appears the issue is because of using an .input-group instead of a .form-group

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
