### ISSUE TITLE
Uncaught TypeError: $ is not a function. With Angular JS

### ISSUE THREAD

**Issue by taimoor736** [almasaeed2010/AdminLTE#1049]
Hello there!
Awesome template. It just stop working with Angular JS. Whenever I click the Menu Hamburger Icon it through me this error "Uncaught TypeError: $ is not a function." But when I reload the window, it start working.
Can't figure out the issue.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
