### ISSUE TITLE
Trouble using .collapse()

### ISSUE THREAD

**Issue by erochaamorim** [almasaeed2010/AdminLTE#1052]
When using bootstrap, one can use .collapse("hide"), and collapse.("show") on collapsable elements to hide or show the content.

I'm using AdminLte's collapsable boxes, and I have a page where I want to make it posssible to expand or retract all boxes when a button is pressed.

I've tried using .collapse() but it didn't work.

I've also tried other approaches, such as:
iterating over each box, removing/adding the "collapsed-box" class, and changing the .box-body display ("none"/"box");
lauching the "click" event on each collapse button;

but nothing worked properly; if you only use the show/hide all button, it's fine, but once you press an individual show/hide button, the behavior for that individual box derrails, and the show/hide all button doesnt works anymore.

I want to know if there's a way to achieve the behavior I want, by lauching the proper behavior trough jQuery.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.

**Comment by erochaamorim** [comment]
Oh, I eventually found a solution. Can't remember it exactly, but it's all good folks!
