### ISSUE TITLE
Sidebar dropdowns toggle twice with JQuery Turbolinks

### ISSUE THREAD

**Issue by doncadavona** [almasaeed2010/AdminLTE#1053]
Using [Turbolinks](https://github.com/turbolinks/turbolinks) with Ruby on Rails, AdminLTE's dropdown sidebar links fire twice when clicked. Eg, on full page reload, there's no problem. But upon clicking  any link after page reload, clicks to sidebar dropdowns make them slide down then slide up immidiately afterwards.

This issue is related to: [https://github.com/kossnocorp/jquery.turbolinks#events-firing-twice-or-more](https://github.com/kossnocorp/jquery.turbolinks#events-firing-twice-or-more)

I've also checked this issue: [https://github.com/almasaeed2010/AdminLTE/issues/563)](https://github.com/almasaeed2010/AdminLTE/issues/563)

**Comment by jmworks** [comment]
I also had same issue and could not fix it by myself, I turned off Turbolinks temporally, if it fixes it helps.

**Comment by doncadavona** [comment]
Just found it's already fixed: [https://github.com/almasaeed2010/AdminLTE/pull/729](https://github.com/almasaeed2010/AdminLTE/pull/729)

I just copied commit on line 391.

**Comment by jmworks** [comment]
oh thanks

**Comment by doncadavona** [comment]
Another issue arises: the Sidebar toggle button doesn't work consistently. Sometimes, when a link is clicked with Turbolinks, the sidebar toggle button won't work, but sometimes it does when another link is clicked. Maybe open a new issue for this?

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
