### ISSUE TITLE
Node package dependency on jQuery

### ISSUE THREAD

**Issue by drbarto** [almasaeed2010/AdminLTE#1055]
Hi,

I'm trying to include the admin-lte node package with webpack. Building works fine, but at runtime an error occurs because the jQuery package is not loaded before AdminLTE (which depends on jQuery). Apparently, the admin-lte package has no dependencies configured.

Now my question: is the dependency omitted on purpose, is this a mistake, or is the package just not intended to be used with webpack?

(Bonus question: any hint on how to use AdminLTE in the context I described?)

Regards,
Martin

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
