### ISSUE TITLE
Sidebar treeview menu opened and reclosed automatically

### ISSUE THREAD

**Issue by twnaing** [almasaeed2010/AdminLTE#1087]
The issue was also reported in issue https://github.com/almasaeed2010/AdminLTE/issues/1053

The issue was fixed in PR https://github.com/almasaeed2010/AdminLTE/pull/729

However, I saw the (supposed unworking) code was reintroduced in `2.3.3` release.

I manually changed and the problematic behavior is corrected.

This is the exact duplicate of PR https://github.com/almasaeed2010/AdminLTE/pull/1001

**Comment by almasaeed2010** [comment]
A fix is being tested. Please see #1094 

If the this doesn't fix it. Please let me know.

Thanks!

**Comment by abonafina** [comment]
good afternoon
I have the latest version and still have the same problem, by clicking on the menu tree it opens and closes without reason

**Comment by avew** [comment]
i have the same proble
![](http://gifyu.com/images/test650b3.gif)

**Comment by JonLev** [comment]
Hi, I want to use this great repo, but with turbolinks for performances and I had the same problem as above.
After reading different issue raised in this repo, I finally found that:
- if you apply what you can found [here (issue 563)](https://github.com/almasaeed2010/AdminLTE/issues/563) it attaches the listener twice because of double call of `$.AdminLTE.pushMenu.activate()` and `$.AdminLTE.layout.activate()` that ends on the result above. Then if you change view, turbolinks make quicker application of assets and remove one of these listener that ends on the perfect result.
- if you remove the `if (options.sidebarPushMenu)` so you solve the issue of when you refresh the page, but then on a turbolinks load, it removes this single event and don't apply the `prevent default` so the button become a simple link to the same page.

It seems the issue happen for all collapsable buttons.
So I wonder if we can still make this work (so close for making this work for good). @almasaeed2010  any idea?

**Comment by JonLev** [comment]
I didn't read all the doc of turbolinks, but I adapt the code to make this work for both sidebars (control and main):
```
var lte_ready = function () {
  var options;
  options = $.AdminLTE.options;
  if ($.turboAlreadyLoaded) {
    if (options.sidebarPushMenu) {
      $.AdminLTE.pushMenu.activate(options.sidebarToggleSelector);
    }
    if (options.enableControlSidebar) {
      $.AdminLTE.controlSidebar.activate();
    }
  }
  $.turboAlreadyLoaded = true;
  return $.AdminLTE.layout.activate();
};
document.addEventListener('turbolinks:load', lte_ready);
```

Hope it helps
