### ISSUE TITLE
sidebar - fa fa-angle-left pull-right inside treeview broken after update from 2.3.3 to 2.3.5

### ISSUE THREAD

**Issue by arysom** [almasaeed2010/AdminLTE#1134]
Firstival - thank you for you work! 

I use newest cdnjs version of AdminLTE css, same thing happen in 2.3.4 . It looks, like this part is missing

```
.sidebar-menu li > a > .pull-right {
    margin-top: -7px;
    position: absolute;
    right: 10px;
    top: 50%;
}
```

And here's the screenshot:

![zrzut ekranu 2016-07-25 o 15 20 08](https://cloud.githubusercontent.com/assets/1759253/17102763/64f41acc-527b-11e6-8218-6ee4abf64755.png)

I can't track myself what has changed. Best regards!

**Comment by ByteHunter** [comment]
I have the same issue and, indeed there is a part missing.
In a recent mergue request #1006 the `.pull-right` class was replaced by `.pull-right-container` which I think has a little sense. If you don't use multiple labels you may want to keep it simple by just specifying `.pull-right` to the `<i>` element.

The problem was reagarding a visual glitch in Firefox (which I could reproduce with my current browser's version **47.0.1**) where multiple labels are not being displayed correctly:
![issue1134-multiple_labels_problem](https://cloud.githubusercontent.com/assets/10613623/17142435/6acc56a0-5350-11e6-96e7-c8a20c83213b.png)
![issue1134-multiple_labels_problem-2](https://cloud.githubusercontent.com/assets/10613623/17142499/a36383c6-5350-11e6-9b68-258caad94206.png)


If you don't use multiple labels consider this workaround (example of a fully dropdown menu):
```html
<li class="treeview">
    <a href="#">
        <i class="fa fa-coffee"></i> 
        <span>Menu</span> 
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="#"><i class="fa fa-circle-o"></i> Submenu 1</a></li>
        <li><a href="#"><i class="fa fa-circle-o"></i> Submenu 2</a></li>
        <li><a href="#"><i class="fa fa-circle-o"></i> Submenu 3</a></li>
    </ul>
</li>
```
And this will fix this visual glitch.
![issue1134-working](https://cloud.githubusercontent.com/assets/10613623/17141631/139d4644-534d-11e6-8f0a-7d60cbe2f911.png)
Working expanded as well.
![issue1134-working-expanded](https://cloud.githubusercontent.com/assets/10613623/17141769/be3d2b28-534d-11e6-9878-c4dc9bc6c557.png)

If you want to add multiple labels, with this change you have to do it enclosing all of them inside a `.pull-right-container`, like this:
```html
<li>
    <a href="#">
        <i class="fa fa-coffee"></i> <span>Menu</span>
        <span class="pull-right-container">
            <span class="label label-success">10</span>
            <span class="label label-warning">20</span>
            <span class="label label-danger">30</span>
        </span>
    </a>
</li>
```
Which will produce:
![issue1134-multiple-labels](https://cloud.githubusercontent.com/assets/10613623/17142083/0f2b48a2-534f-11e6-822c-b347fcd26144.png)

However, if you still want all these features (dropdown's caret and multi-label) consider enclosing them all in the `.pull-right-container`, like the following snippet:
```html
<li class="treeview">
    <a href="#">
        <i class="fa fa-coffee"></i> 
        <span>Menu</span> 
        <span class="pull-right-container">
            <span class="label label-success">10</span>
            <span class="label label-warning">20</span>
            <span class="label label-danger">30</span> 
            <i class="fa fa-angle-left"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li><a href="#"><i class="fa fa-circle-o"></i> Submenu 1</a></li>
        <li><a href="#"><i class="fa fa-circle-o"></i> Submenu 2</a></li>
        <li><a href="#"><i class="fa fa-circle-o"></i> Submenu 3</a></li>
    </ul>
</li>
```
The result will be:
![issue1134-treeview_and_multilabel](https://cloud.githubusercontent.com/assets/10613623/17142263/ca323732-534f-11e6-885f-fe353ae243cd.png)

I'm not a big fan of this change, since I personally didn't use multiple labels. And single labels worked perfectly fine, as well as dropdown's caret. If there is no way to easily fix this issue in Firefox, both css classes (`.pull-right` and `.pull-right-container`) should be kept to handle both cases and to not break all people's implementations.

**Comment by Hokwang** [comment]
I am suffering same case, and I am waiting netxt patch version.
In my case, fa-angle-left is not changing to fa-angle-down icon.

**Comment by michaelarnauts** [comment]
This can be solved by wrapping the icon in a `<span class="pull-right-container">`, and keeping `pull-right` on the icon itself. Actually, I think this is the recommended solution since the examples are also modified like this.

**Comment by arysom** [comment]
I watched examples and haven't noticed. You are more observant :). Thank you, it works.  

<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>

**Comment by Hokwang** [comment]
@michaelarnauts Sorry, but where is example?

**Comment by michaelarnauts** [comment]
In `index.html`. https://github.com/almasaeed2010/AdminLTE/blob/master/index.html#L385
