### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by arra-sy** [almasaeed2010/AdminLTE#1162]
I had a problem on a sidebar dropdown can not collapsing after ajax request to load other php page, displaying error: Uncaught TypeError: Can not read property 'options' of undefined: app.min.js: 13

Before i was looked in this thread : https://github.com/almasaeed2010/AdminLTE/issues/253

but i don't know alternate solution what him means with "I have used the asset bundle instead and now it is working fine."

**Comment by b8ne** [comment]
Getting the same error, at `var e=$($.AdminLTE.options...`

**Comment by alexli0707** [comment]
I got the same error.I am using jinjia2 and requirejs to build fronted.

**Comment by b8ne** [comment]
Just updated to latest release, still getting this issue. My dropdowns are going down, but issue occurse when trying to got back up.  Any work being done on this?

**Comment by almasaeed2010** [comment]
Hello @b8ne 

The error does not occur on the demo. Could you please provide more information about your implementation. Are you using AdminLTE as part of an AngularJS or ReactJS project? Which browser does this error show up on? Are there any other errors before or after it? Any other information that may be helpful could help us debug your issue better. 

Thank you for reporting your issues!

**Comment by b8ne** [comment]
Hey @almasaeed2010 
Im currently using the library in a Laravel PHP project.
Just double checked my implementation and it matches your examples.
I use Chrome, however the issue is present on firefox and safari too.
See below for console errors after simply clicking once to expand and again to close a sidebar tree.
<img width="1280" alt="screen shot 2017-01-14 at 6 26 53 pm" src="https://cloud.githubusercontent.com/assets/19263633/21953299/24a7bdf4-da87-11e6-9d7d-9a5c2246ed8a.png">

**Comment by almasaeed2010** [comment]
In that case, the best way for me to debug this is a link to your implementation. So far, I am not getting this error in any of the demo pages. Can you publish and provide a link?

**Comment by farismohammed** [comment]
Getting the same error... I'm also stuck. help me..
