### ISSUE TITLE
Possible mispell for enableBSToppltip option

### ISSUE THREAD

**Issue by aocneanu** [almasaeed2010/AdminLTE#1175]
Is this how it's intended to be named or this is a mispell?

From doc:

  var AdminLTEOptions = {
    //Enable sidebar expand on hover effect for sidebar mini
    //This option is forced to true if both the fixed layout and sidebar mini
    //are used together
    sidebarExpandOnHover: true,
    //BoxRefresh Plugin
    enableBoxRefresh: true,
    //Bootstrap.js tooltip
    **enableBSToppltip:** true
  };

**Comment by zburk** [comment]
I'm going to guess no because in `dist/js/app.js`, which is what the documentation refers to, there's the following:
`{
  //Enable sidebar expand on hover effect for sidebar mini
  //This option is forced to true if both the fixed layout and sidebar mini
  //are used together
  sidebarExpandOnHover: false,
  //BoxRefresh Plugin
  enableBoxRefresh: true,
  //Bootstrap.js tooltip
  enableBSToppltip: true,
}`

**Comment by almasaeed2010** [comment]
Unfortunately, it is misspelled. However, we can't change that now since it would break backwards compatibility.
