### ISSUE TITLE
AdminLTE removes active class on sibling sidebar item

### ISSUE THREAD

**Issue by cyrilchapon** [almasaeed2010/AdminLTE#1209]
I'm using ng-class to toggle "active" state on sidebar menu items.

Though, when clicking a "multilevel" button (another button), it removes "active" class on all other menu items. Even worse, when we close the menu (reclicking on multilevel), it doesn't set's .active back on previously activated menu item, loosing the information in the process.

Is there a way to disable the dynamic behavior of .active class in multilevel ?

**Comment by almasaeed2010** [comment]
Unfortunately, you will have to edit ```app.js``` itself to do that. Specifically, lines 405-422-423.

Changes on our would be difficult since it would break backwards compatibility. This issue has been addressed in version 3.0.0-alpha-1, which has not been released yet. We apologize for the inconvenience.

Thanks!
