### ISSUE TITLE
Idea: communication portals.

### ISSUE THREAD

**Issue by Tjoosten** [almasaeed2010/AdminLTE#1215]
What if adminLTE get a gitter or slack channel for users. That have problems that are not bugs in the source code?

**Comment by FlickTheManual** [comment]
I'm ok with that idea, it can be more effective for github if we can split bug source and question/idea with discussion/troll and cleaning the gitlab bug tracking. Btw i think we can «proify» the source tracking. Good luck for rest Best regardSend from Huawei KIW-L21-------- Message original --------Objet : [almasaeed2010/AdminLTE] Idea: communication portals. (#1215)De : Tim Joosten À : almasaeed2010/AdminLTE Cc : What if adminLTE get a gitter or slack channel for users. That have problems that are not bugs in the source code? 

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/almasaeed2010/AdminLTE","title":"almasaeed2010/AdminLTE","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/almasaeed2010/AdminLTE"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Idea: communication portals. (#1215)"}],"action":{"name":"View Issue","url":"https://github.com/almasaeed2010/AdminLTE/issues/1215"}}}

**Comment by almasaeed2010** [comment]
I like your suggestion. Although I might not have time to be on the channel all the time but the community might find it useful. Here is a sign up page for Slack:

https://adminlte.signup.team/

Thanks!
