### ISSUE TITLE
Laravel is not able to access resources when route like "/orders/list" but access them when  "route/orderlist"

### ISSUE THREAD

**Issue by mfadel85** [almasaeed2010/AdminLTE#1225]
Hello every,
I integrated LTE-Admin with my current app, when I type 
http://localhost:8000/orderslist
it reaches all resources : js, css, images,
but when accessing http://localhost:8000/orders/list
it shows  missing resources,  like this message

Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost:8000/orders/dist/css/skins/skin-blue.min.css

I want to use this route '/orders/list' not this '/orderslist', how can I solve failed to load resources error???

these are the routes:
Route::get('/orderslist','OrdersController@showReadyOrders');
Route::get('/orders/list','OrdersController@showReadyOrders');

**Comment by kressly** [comment]
Is that not a directory or an Htaccess problem rather than an adminlte problem ? 

For u to access through an url that u do not have, u will have to either set an Url rewriting rule in htaccess or move ur folder to where u want them to be

**Comment by anishmohan** [comment]
In Laravel, you can use the helper function asset.

Optional: Also instead of using localhost, if using Apache as web server
for development you can add virtual host and add an entry in vhost.conf to
update url as myapp.dev.

Issue you are encountering here is all your url is redirecting to routes
instead of actual file. Check you have a resource controller route to
OrdersController

<link href="{{
asset("/bower_components/adminlte/dist/css/AdminLTE.min.css")}}"
rel="stylesheet" type="text/css" />{{-- Theme style --}}

<script src="{{ asset ("/bower_components/adminlte/dist/js/app.js") }}"
type="text/javascript"></script>{{-- AdminLTE App --}}

**Comment by arianmaykon** [comment]
I dont think this repository has nothing to do with Laravel or any framework.
I do recommend close/ignore the issue.

**Comment by almasaeed2010** [comment]
Hello @mfadel85 

You will need to make sure you link all your assets using the absolute path rather than a relative path.

See: http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

Thanks!
