### ISSUE TITLE
sidebar collapsed hover windows auto width?

### ISSUE THREAD

**Issue by t0n1zz** [almasaeed2010/AdminLTE#1235]
![screenshot 1](https://cloud.githubusercontent.com/assets/6964548/19842035/0bf1cf5a-9f47-11e6-8817-09e55d2dfccb.jpg)

so as you can see up there.. the windows that appear when i hover into the collapsed sidebar, i think it is have a fixed size and not an auto width that will match how many character in the list written... 

so how to fix this kind of issue?

**Comment by XzAeRo** [comment]
I've been playing with this for a while, and there's a major problem with the way these menus work.

According to the current syntax for the menu:

```html
<li class="treeview">
  <a href="#">
    <i class="fa fa-cogs"></i> <span>Example</span>
    <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
  </a>
  <ul class="treeview-menu">
    <li class="treeview active">
      <a href="#">
        <i class="fa fa-flag"></i><span>Really long text that overflows</span>
        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
      </a>
    </li>
  </ul>
</li>
```

The current syntax doesn't allow automatic sizing, because it's using the `display: absolute` property to show the submenu (unless this is implemented via JS?).

But if you really need to add extra space for the elements, you need to override these two rules: the [`.treeview-menu` element](https://github.com/almasaeed2010/AdminLTE/blob/master/build/less/sidebar-mini.less#L60), and the [`.pull-right-container` element](https://github.com/almasaeed2010/AdminLTE/blob/master/build/less/sidebar-mini.less#L75) width properties.

The text overflow itself just needs minor tweaking, so I will submit a PR for that.

On the other hand this bug has made me respect even more @almasaeed2010. Dealing with all these CSS rules gets hard really quick.

**Comment by almasaeed2010** [comment]
Refer to #1294
