### ISSUE TITLE
[SUGGESTION] Remove Glyphicons and Ionicons

### ISSUE THREAD

**Issue by vincent-guesnard** [almasaeed2010/AdminLTE#1304]
Hello,

Loading fonts is fun but it's heavy. On my fork of AdminLTE, i've decided to purge Glyphicons from Bootstrap and remove Ionicons. Honestly, we have have all we need within FontAwesome, why load something else ?

I'm currently thinking on a base64 distribution of fonts files within FontAwesome CSS. If i manage to do something working correctly, i'll let you know.

Best regards,

Vincent

**Comment by chris-rutherfurd** [comment]
Strictly speaking I don't think there would be any need to remove Glyphicons or Ionicons from the library. The web developer can choose to ommit them from the final page and ensure speedly page loads by simply not incorporating the links to them in the markup. In that way they are still available should they be desired at a later date or by someone else who downloads the main repo but doesn't affect the page load of anyone who decides that they don't need them for their site.

**Comment by REJack** [comment]
I think this will be happen with v3, if @almasaeed2010 use bootstrap v4 for it.

http://v4-alpha.getbootstrap.com/migration/
> ### Components
> ...
> Dropped the Glyphicons icon font. If you need icons, some options are: 
> ...

**Comment by almasaeed2010** [comment]
Hello @vincent-guesnard,

AdminLTE makes it super easy to remove the icons that you won't use. They are there just to show that AdminLTE supports theses icons. However, in v3, icons are going to be even more optional in that they won't be included in any CSS files. Also, we will provide support for font-awesome only since it has the most versatile collection. That is not to say that other icons can't be used because we added an ```.icon``` class that applies the changes to any icon font you'd like making it even more powerful.

Thanks for the suggestion!
