### ISSUE TITLE
Have you another payment method?

### ISSUE THREAD

**Issue by wokster** [almasaeed2010/AdminLTE#1315]
I try to buy it:
https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S
But have an error on paypall. "The seller does not accept Your card"
I try 2 diferent card (visa & master) - the same error.
Have you another payment method?

**Comment by REJack** [comment]
Ask WrapBootstrap.com about your problem, AdminLTE is not from WrapBootstrap. 

Mit freundlichen Grüßen
Raphael Jackstadt

Von meinem iPhone gesendet

**Comment by wokster** [comment]
i try to buy AdminLTE premium template. So i want know  - can i do it without WrapBootstrap. Becouse WrapBootstrap - have only one payment method and it does not work.

**Comment by REJack** [comment]
AdminLTE is a Free Premium Admin Control Panel Theme. 
INSPINIA isn't from AdminLTE's Creator, i think you are wrong here. 

Mit freundlichen Grüßen
Raphael Jackstadt

Von meinem iPhone gesendet

**Comment by wokster** [comment]
This is site: https://almsaeedstudio.com
This is support link on this site: https://github.com/almasaeed2010/AdminLTE/issues
This is premium template page on this site: https://almsaeedstudio.com/premium

> INSPINIA isn't from AdminLTE's Creator

Really?

**Comment by almasaeed2010** [comment]
Hello,

INSPINIA is sponsored by Almsaeed Studio but its authors are a completely different group that otherwise has no association with Almsaeed Studio. We apologize for the confusion! You may contact the authors of INSPINIA using the form on this page: https://wrapbootstrap.com/user/WebAppLayers (you may need to sign up first).

Thanks!
