### ISSUE TITLE
AdminLTE in Joomla(cms)

### ISSUE THREAD

**Issue by DarkNito** [almasaeed2010/AdminLTE#1325]
Hi everyone and congratulations for the amazing dashboard. My question is simple (maybe the answer it is not): is it possible to use this dashboard in my joomla website?

Thanks.

**Comment by Tjoosten** [comment]
yes. It can you only need to weave it in the Joomla logic

**Comment by almasaeed2010** [comment]
Hello @DarkNito, 

Since AdminLTE is an HTML template, you can implement it in any customizable CMS that you'd like. Unfortunately, it is not exactly an easy task. It requires extensive knowledge of the CMS framework.

I looked around but couldn't find an existing implementation at this time. 

Thanks!
