### ISSUE TITLE
Wondering if v3-dev branch is ready to test

### ISSUE THREAD

**Issue by ghost** [almasaeed2010/AdminLTE#1327]
Hey Almasaeed,

I'm wondering if the v3 branch is ready to test in a test project? 

Cheers

**Comment by almasaeed2010** [comment]
Hello @JayteeNZ, 

Unfortunately, it is not yet ready since most of the layout options have not been implemented yet. It is also in very early stages in that many of the components such as the "box" will be removed and replaced with "BS4 cards". We are hoping to release an alpha version that is testable by mid February if time permits. 

Thank you for your interest in helping us develop v3. I'll keep this post open until the announcement of an alpha release. 

Thanks!

**Comment by almasaeed2010** [comment]
It's now ready for testing.
