### ISSUE TITLE
Height of box-content not resizing to highcharts graphs

### ISSUE THREAD

**Issue by luskbo** [almasaeed2010/AdminLTE#1362]
I am using the content class section to hold a box class with a highcharts graph inside of it.
```
<section class="content">
      <!-- Default box -->
          <div class="box">
            <div class="box-header">
			</div>
			<div class="box-body">
               <div id='chartID'></div>
            </div>
          </div>
    </section> 
```

When using the chart without the adminLTE template, I can set the height to 100% like as seen in this jfiddle: [http://jsfiddle.net/wkkAd/149/](http://jsfiddle.net/wkkAd/149/)

When I place the chart in the adminLTE template, the height attributes are not resizing the graph to fit 100% of the box.
The only way I can change the height is by manually setting the height of the graph by pixels and not by percentage.
The highcharts documentation states that the height of the graph is dynamically as long as you set a height on the chart's containing element. It can be a fixed number or a even a percent if position is absolute.

The box class already has a default height of 100%, and setting the box-body to 100% doesn't work either. 

Any ideas on how to make the content within the box or box-body class all 100%?

**Comment by almasaeed2010** [comment]
Hello,

This is a bit of tough one. In order to get all of the containers of the graph to have a specified width then you need to set all of it's parent components individually.

I would try doing this in JS before initializing the graph:
```js
$('#graph").parents().each(function(){
  $(this).css('height', '100%');
})
```

I have a feeling this will cause all sorts of other issues, but deserves a try.

I am sorry we can't help you any further here since this wouldn't be an issue that is directly related to an AdminLTE feature. Sorry for the inconvenience.

Thanks!
