### ISSUE TITLE
Question: .content with "display: table"

### ISSUE THREAD

**Issue by MarcReniu** [almasaeed2010/AdminLTE#1495]
Hello there,

I'm working with V3, and I notice that exists a rule in `.content` class I'm struggling with, in *_layout.scss* file.
```css
.content-wrapper {
  > .content {
    display: table;
    width: 100%;
  }
}
```
My question is: **Is `display: table` the correct rule?** I tried to use `inline-block` as an alternative, and seems to work as well.

This change is because horizontal-scrolled tables doesn't catch width correctly with `table` configuration, but `inline-block` do the work.

**Comment by almasaeed2010** [comment]
Hello @MarcReniu 

v3 is work in progress. This is absolutely just a test attempt and will be removed once we resume working on v3. For the record, you should just remove the `display: table` line. Also, there are so many issues in v3 at this point and it'll take some time until we can fix them since Bootstrap 4 has not been officially released yet.

Thanks!
