### ISSUE TITLE
License issue with jVectorMap

### ISSUE THREAD

**Issue by toddjames** [almasaeed2010/AdminLTE#1616]
AdminLTE is licensed under the MIT license. Every single one of the libraries it uses is also licensed under the MIT license or a compatible license, with the exception of bower_components/jvectormap/.

The version of jvectormap at bower_components/jvectormap/ is 2.0.4. As of version 2.0, jVectorMap is dual-licensed under GPL and a commercial license.

This single library causes issues for anyone who would like to use AdminLTE under the terms of the MIT license, unless they want to rip jVectorMap out or revert to 1.2.2, which is the last version licensed under the MIT license.

Note that plugins/jvectormap/ is version 1.2.2, which IS licensed under the MIT license.

**Comment by dboggs95** [comment]
I am not a lawyer. I am not licensed to give legal advice. This is just my opinion of a safe route for the developers and users of the project after reviewing the code and the relevant licenses for each library. 

According to the web site of jVectorMap, the commercial license has to be paid for. It is not an option that we can freely download the code and choose to use.

The last version of AdminLTE to use jVectorMap 1.2.2 under MIT is 2.3.11.

I don't understand why the plugins folder is still there. I can see that the project what updated to use a package manager called Bower, and the sample indices link to jVectorMap in the bower_components folder. That makes the plugins folder obsolete, meaning the version of jVectorMap being used is the AGPL version, which means that AdminLTE must either switch its license to AGPL or downgrade jVectorMap back to version 1.2.2. 

If you don't know the difference between AGPL and GPL, AGPL considers the users of a site the clients, while the GPL considers the server of the site the client, meaning you must distribute the code of your web application to your users under AGPL, whereas GPL means that your code must be available to the server that hosts it. That might be a little off, but that is the basic idea.

Another legal consideration is that a couple other libraries have multiple licensing options. In order to use them, it is best to have a legal.txt that specifies which ones. CK Editor 4 has three licensing options, so it should be entered into the legal.txt as LGPLv2.1. jQuery-Slimscroll also has two options, so for this library the MIT license should be specified in the legal.txt. AdminLTE does not do this, but to my understanding, in order for AdminLTE to be MIT licensed these need to be specified. 

In light of all of this, in order to safely use this template, I would do a few things. First, use version 2.3.11 in to have the correct version of jVectorMap . Second, create a legal.txt that specifies that CK Editor 4 is used under the LGPLv2.1 license and jQuery-Slimscroll under the MIT license. Third, create a credit page on the web application with links to all of the plugins used and to AdminLTE; also include the licenses under which each is used. Finally, I don't know whether minifying libraries together is a consideration for anybody (I don't know that that's a thing developers do with third party libraries), but I would also refrain from minifying CK Editor 4 with anything else, because I don't have a clue what counts as statically and dynamically linked for web applications. 

If care is taken with each plugin, I don't see why any applications built with AdminLTE can't be licensed under MIT, Apache, BSD, or even as closed source software. If any of my reasoning is flawed, please challenge it.

**Comment by toddjames** [comment]
@dboggs95 I am also not a lawyer and nothing here should be taken as legal advice, but I agree with most of what you've written.

Two points of clarification that I can see:

> According to the web site of jVectorMap, the commercial license has to be paid for. It is not an option that we can freely download the code and choose to use.

AFAIU, the code is the same, you simply choose which license to use. The open source license or one of the two commercial licenses, whose full terms I cannot see currently because the link is broken.

Lastly, it is not completely clear whether jVectorMap 2.0+ is licensed under GPL or AGPL. In this issue, I originally assumed GPL, because that is what is listed on their website. After double checking today, in their GitHub repository, they changed the open source license file from GPL to AGPL in 2015. It seems that the website is *probably* just outdated, but I've opened [an issue](https://github.com/bjornd/jvectormap/issues/445) for them to hopefully clarify and fix the offending incorrect information (and broken link to the commercial terms).

I don't foresee this issue being addressed any time soon, so I suppose it would be wise for anyone using AdminLTE for commercial purposes to simply remove any reference of jVectorMap or spring for one of the two commercial licenses if required, depending on your deployment strategy (e.g. cloud-hosted vs. Docker image). Maybe the situation will change in AdminLTE 3.0.

**Comment by dboggs95** [comment]
@toddjames 
Here is the link to their pricing page.
[jVectorMap - licenses and pricing](http://jvectormap.com/licenses-and-pricing/)

It says the commercial and development licenses have to be paid for in order to use them. It seems to me that licensing issues are ambiguous no matter which way you go. If AdminLTE pays for a license, it does not transfer to their users; I have no clue whether that makes it an unlicensed copy when someone downloads it, or just defaults it to AGPL. If AGPL is chosen as the license for jVectorMap, that would mean that AdminLTE has to be AGPL, which would make it worthless to business users who are not willing to release their source code. 

In order for AdminLTE to continue to be unambiguously MIT licensed, it appears they must either downgrade jVectorMap to 1.2.2, make their own mapping library, or find an alternative with an Apache, BSD, CC, or MIT license. I don't want to work off of any of the 2.4.x versions because I think they might legally be AGPL licensed instead of MIT.

**Comment by almasaeed2010** [comment]
Thank you all for pointing out the license issue. We'll add a notice about this issue on the repo and downgrade jVectorMaps to 1.2.2 for the next release!

Thanks!

**Comment by almasaeed2010** [comment]
Available in both v3.0.0 and v2.4.7
