### ISSUE TITLE
Clean v2.4.0 installation

### ISSUE THREAD

**Issue by fra87** [almasaeed2010/AdminLTE#1653]
Hi
Sorry if this is a noobish question, but I'm not very much into bower/npm/other to be able to answer myself.
I used an older version of AdminLTE and the downloaded file was clean: one folder for bootstrap, one for external plugins, one for the documentation, and it was clear what I had to keep and what to remove. I downloaded the v2.3 release and it it organized the same.
Now, for the 2.4.0 rc version, the number of folders increased, there are a lot of what I perceive as garbage files (json docs for bower and npm, for instance), and in general it is not very much clean.
Is this because of being a release candidate or not? How can I clean it keeping only the "really useful" files? What I'd like is a sort of "production ready" package
Thank you

**Comment by almasaeed2010** [comment]
Hello @fra87 

Excellent question! As development practices progressed, the majority of developers use a package management software to manage their product's dependencies. Tools such as `npm` and `bower` are becoming increasingly popular and for good reason. You can learn more about [npm here](https://www.npmjs.com/).

If you are not using those tools, you'll need to manually copy over the distribution files (js, css, html, etc) from each package's folder. However if you use npm, for example, you can automate the process using various plugins (such as webpack, gulp or grunt).

The amazing power package management software provides falls short when it comes to simple downloads in that you'll need to download the entire project rather than only the compiled version. Unfortunately, with AdminLTE at least, there isn't a method to download only what's required without using a package management tool.

Sorry for the inconvenience.

Thanks!
