### ISSUE TITLE
Add select2 to form element

### ISSUE THREAD

**Issue by ikhsan017** [almasaeed2010/AdminLTE#17]
Hi There,

Just want to say thanks for your great work. So far, this is the best free theme with premium quality and professional touch I've found.

By the way, It would be great If we can integrate select2 plugin into the form element. If you agree, I would love to fork and implement it.

Best regards
Ikhsan

**Comment by victorleal** [comment]
I don't know if there is some advance here (this issue was opened a long time ago), but I was doing the same thing: trying to use *select2* besides the AdminLTE theme.

In my implementation it looks good, it does not fit perfectly (it is missing the *select2* images, and I still don't know why) but it works fine. It was just necessary to put the `select2-bootstrap.css` file also.
