### ISSUE TITLE
Webpack support (boxed-bg.jpg is missing)

### ISSUE THREAD

**Issue by Onset** [almasaeed2010/AdminLTE#1789]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4

### Description:
Webpack won't work with `@boxed-layout-bg-image-path: "../img/boxed-bg.jpg";`. The actual location is `"../../dist/img/boxed-bg.jpg"`.

Locating the image file in `dist` folder only is misleading

**Comment by almasaeed2010** [comment]
After compiling LESS, the file resides in `../img/boxed-bg.jpg`. As addressed in #1802, this is a webpack problem that you may be able to fix using some setting to ignore where assets are placed.

In the long run, I think restructuring AdminLTE to have its `scss` folder in the same folder as the destination `css` folder will fix the issue since referneces assets will be in the same path. But we can't implement this solution until AdminLTE 3.0.

Thanks!
