### ISSUE TITLE
i'm i installing it as wordpress theme or plugin

### ISSUE THREAD

**Issue by zuckerbels** [almasaeed2010/AdminLTE#1890]
please how do i use this. I'm i going to install it as a wordpress theme or plugin?  beause i installed as wordpress theme, it showed error. Thank you.

**Comment by Muneera-Salah** [comment]
Hi ,,
you can't use this theme directly as Wordpress theme , because AdminLTE build as static pages (HTML , CSS , Js) .
you need to use this theme by embedded php on it , to be dynamic. 
Wordpress CMS have documentation to build theme or plugin check 
official site :
https://developer.wordpress.org/

**Comment by zuckerbels** [comment]
Perfect answer. I appreciate your answer. Sorry i am just a new developer and was hoping to get a little support to use it. Your answer helped greatly.  Thank you.
I am on https://developer.wordpress.org doing some good research. Please can you assist on how i can embedded php on it , to be dynamic? Thanks in advance.

**Comment by dexit** [comment]
Yes, please follow the instructions you found on https://github.com/erhankilic/AdminLteWpTheme
And bower usage is a 5minute video.

To know more
Please open: https://developer.wordpress.org/themes/getting-started/
