### ISSUE TITLE
AdminLTE version 3 not working with bootstrap modal

### ISSUE THREAD

**Issue by ds-manish** [almasaeed2010/AdminLTE#1897]
bootstrap model is not working.

while clicking on the button it just shows black overlay but modal is not shown.

I even tried copying the code from bootstrap.

**Comment by TimmKroe** [comment]
Could you paste some code in here ?

**Comment by almasaeed2010** [comment]
Hello @ds-manish 

We've tested the bootstrap modals by directly copying from the bootstrap 4 examples and it worked perfectly for us. Are you sure you have the correct markup?

<img width="1440" alt="screen shot 2018-07-15 at 12 05 43 pm" src="https://user-images.githubusercontent.com/1512664/42735750-8741e22e-8827-11e8-81f1-714c741ff3e5.png">


Thanks!

**Comment by ds-manish** [comment]
thanks, seems like mine issue..

**Comment by kaderkarakus** [comment]
old version does not work in the new version error continues
![adsiz](https://user-images.githubusercontent.com/45363631/49733308-2d493f80-fc92-11e8-8a91-a006d3d2d185.png)

**Comment by krishrebats** [comment]
![image](https://user-images.githubusercontent.com/41939888/50735204-f7d03d00-11d0-11e9-82e6-d47742493458.png)

Me too have the same problem

**Comment by luchmewep** [comment]
Hello, Sir @almasaeed2010 ! 

On Admin LTE 3, there is no modals section. I badly need it, Sir. The one uploaded on Github repo does not have that "Launch Demo Modal" button at "Starter Page". I guess you have uploaded the wrong version or something. Modal is really important to make my sample website cooler. I hope you can upload Alpha 3.0.1 or something? Badly need your help, Sir.

Here's a screenshot. I can't edit your css and js codes because I am not good with neither Javascript nor CSS so I need your wisdom on this one, Sir.

So far, Admin LTE 3 is the best in my opinion. It feels like it is approachable, elegant, and interesting at the same time.

![tempsnip](https://user-images.githubusercontent.com/26067874/52264285-32fa9300-296c-11e9-934c-d8550dba3ff4.png)

**Comment by FORHADRAHMAN** [comment]
When clicking on Edit button its just shows black overlay. Pls help
![adminlte](https://user-images.githubusercontent.com/31016235/52969307-12a1ee00-33da-11e9-92f8-7cf35f432c27.JPG)

**Comment by NoitaminAoki** [comment]
i recently experienced it.

You only need to change the z-index on the main sidebar container to 1040

<! - Main Sidebar Container ->
  aside class = "main-sidebar sidebar-dark-primary elevation-4" style = "z-index: 1040! important;"

**Comment by NoitaminAoki** [comment]
> 
> 
> Hello @ds-manish
> 
> We've tested the bootstrap modals by directly copying from the bootstrap 4 examples and it worked perfectly for us. Are you sure you have the correct markup?
> 
> <img alt="screen shot 2018-07-15 at 12 05 43 pm" width="1440" src="https://user-images.githubusercontent.com/1512664/42735750-8741e22e-8827-11e8-81f1-714c741ff3e5.png">
> 
> Thanks!

i recently experienced it.

I only need to change the z-index on the main sidebar container to 1040

<! - Main Sidebar Container ->
aside class = "main-sidebar sidebar-dark-primary elevation-4" style = "z-index: 1040 !important;"

![modal](https://user-images.githubusercontent.com/23255231/56566074-0ace1800-65dc-11e9-8504-a2a6cd49de95.png)

**Comment by olatmi26** [comment]
I solved mine by doing this
 .modal-backdrop {    
    height: auto;
}
