### ISSUE TITLE
Modals... There or not?

### ISSUE THREAD

**Issue by thomsol** [almasaeed2010/AdminLTE#238]
First off... GREAT Template!!

You seem to be conflicted on Modals... Some pages it's there, under UI Elements, others its not.  Where it is there, nothing seems to be modal.  Have you considered integrating Magnific Popup (http://dimsemenov.com/plugins/magnific-popup/)?

**Comment by almasaeed2010** [comment]
Thank you!

I am not following your logic though. Modals are available in the main Bootstrap files and you can use them in any page. AdminLTE restyles the modals (aka dialogs) to fit the design and create consistency. If you'd like to know how to make use of a modal vist [Bootstrap Modals documentation](http://getbootstrap.com/javascript/#modals).

**Comment by ETNyx** [comment]
Once you have started topic about modals,.. I was looking for some notification plugin in AdminLTE. I believe Bootstrap Modals doesnt fit well for this work, I'm thinking about implementing Toastr to mine project base on AdminLTE. Maybe you will like it. (or something different?)

demo: http://codeseven.github.io/toastr/demo.html
github: https://github.com/CodeSeven/toastr

**Comment by lenamtl** [comment]
I'm using a lot of Bootstrap modal with this template and I have no problem.

**Comment by thomsol** [comment]
I'm OK closing this issue... I was not aware of the bootstrap modal capability.  There is an inconsistency in the menuing, some pages show a link to modal, others do not.  Also the current modal page does not work properly (at least on the version I had).

**Comment by almasaeed2010** [comment]
@thomsol please let me know what is not working properly?

**Comment by thomsol** [comment]
Two Things...

When I go to the modal page, I see the boxes, but none of them are being triggered as modals, nor are there any buttons to launch them.

Second, on many pages, there is not a modals link on the side menu.  For example, on the dashboard it's there, if I go to Charts->Flot, there's no modal submenu on the sidebar menu.

Thanks!

**Comment by almasaeed2010** [comment]
The modals page show you the different styles of Bootstrap modals that you can implement. By adding modal contextual classes to the ```.modal``` div you get the effect. Contextual classes are
- ```.modal-primary```
- ```.modal-success```
- ```.modal-danger```
- ```.modal-info```
- ```.modal-warning```

If no contextual class was added, the default class will be applied automatically. The modal system uses Bootstrap's JavaScript implementation, which gives you the ability to launch via data attributes by adding them to buttons, links, etc. However, your idea of giving examples by using specific launch buttons sounds like a good one. I will try to show examples on the modals page. 

To address your second issue, AdminLTE 2 is in its Alpha stage, which means that there will be issues like missing links, broken links, layout changes, and so on, periodically. This suggests that you should not use this version in production just yet since it has not been fully tested and the implementation of features is incomplete. That being said, the latest version in the master repo should have all links to modals and new links to layout options. 

Finally, to get notified of the new production-ready version of AdminLTE 2.0, please [subscribe here](http://almsaeedstudio.com/#subscribe) if you haven't already done so. We appreciate your patience.

**Comment by thomsol** [comment]
Thank You... I've ported your template into Yii 2.0, and love it due to its simplicity.  Many commercial templates have a ton of JS add-ons, which tend to just confuse the issue.  For an "alpha", it has very few issues, just noting the ones I find.  It's truly great!  

One feature request, is the ability to collapse the menu bar to be icons only... :-)

**Comment by jonathanment** [comment]
I'm also battling with Modals.....  very strange - I'm been using Bootstrap for many years now - and I'm pretty sure I'm invoking the modal correctly - as per previous implementations - however, when I invoke it using your template - the screen dims (like it should) but the actual modal doesn't appear.

When I look in the console view - there are no errors.

Any idea where I should start looking?

**Comment by cristianoso19** [comment]
@jonathanment the same problem here, you solved this issue?

**Comment by lenamtl** [comment]
Maybe the modal is under another template element...
If this is the case, you will need to play  with **z-index** in your CSS.
https://www.w3schools.com/cssref/pr_pos_z-index.asp

Bootstrap default .modal use to be z-index:1050 (not sure if it's still the case).

The modal may inherit some of the parent element value.
Let say the div where the modal is place have **position:fixed** then you will have issue with the modal.

**Comment by Gargaroz** [comment]
I experienced this issue while using [Angular-UI modal directive](http://angular-ui.github.io/bootstrap/#!#modal) and in the modal's actual template I had something like this:
```html
<div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">header stuff...</div>
      <div class="modal-body">body stuff...</div>
      <div class="modal-footer">footer stuff...</div>
    </div>
  </div>
</div>
```
Well I noticed that the Angular UI already renders this:
```html
<div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>
```
so I was seeing no modal due to this block above repetition.
