### ISSUE TITLE
Dropdown in class main-header doesnt work!

### ISSUE THREAD

**Issue by douglasduartetb** [almasaeed2010/AdminLTE#249]
I'm having some problems with this classe "navbar-custom-menu", on clicking in element with the class = "dropdown-toggle" just doesn't work, so i tried put 'fixed' in the body element and works fine. Thats strange, because the example pages works fine in another folder, i'm accessing of localhost. Someone had this problem?

**Comment by douglasduartetb** [comment]
Aparentement lacked Some library

**Comment by kressly** [comment]
So were you able to solve your problem ? Because it works fine with me. Which browser are you using ? if it is Mozilla firefox, then do not use the cdn, download all additional files and link to them because mozilla has a problem with some CDN https.
There is an article on it on StackExchange
http://meta.stackexchange.com/questions/248587/stack-exchange-french-login-page-does-not-display-well-in-mozilla-firefox-on-my/248589#248589

**Comment by douglasduartetb** [comment]
I'm using Chrome, but i tested on firefox to and had the same problem, but aparently the problem is gone. I usually download all the dependencies, always. thanks :)

**Comment by chlebta** [comment]
@douglasduartetb did solved it ? I got the same issue

**Comment by douglasduartetb** [comment]
@chlebta I solved but i stop use this template to create my own, but you can try add all librarys again to see if you dont forgot anything

**Comment by c-desmarais** [comment]
I am experiencing the same issue. Did anybody find a specific solution to this ? What exactly, is the name of the missing library that's needed? Cuz i've been checking again and again, and don't really find the source of the problem. Thanks in advance.

**Comment by douglasduartetb** [comment]
@c-desmarais you need to put all the parts of the template on html, like 

> `<header class="main-header">.`

> `<aside class="main-sidebar">`

> `<div class="content-wrapper">`
