### ISSUE TITLE
Invoices are printed only as grayscale

### ISSUE THREAD

**Issue by realjumy** [almasaeed2010/AdminLTE#294]
Hello all.

I'm impressed with AdminLTE. It will be a great way to control some of my websites.

However, I have a problem. I tried to use the invoice example to make a "summary printer" but no matter what I do, the text is going to be printed always in grey-scale.

I searched the CSS code searching for filters but I can't found any related with the text to remove the colors.

Any of you can give me some guidance about how to solve it? I don't know if I'm doing something wrong or if it is a problem with the panel.

Thanks.

**Comment by lenamtl** [comment]
Hi,
Bootstrap Print CSS, print in black only.
check Bootstrap.css line 192 and 196
@media print {

**Comment by almasaeed2010** [comment]
Hi,
AdminLTE doesn't apply this kind of restriction. However, I see your problem and I suggest you consider asking the Bootstrap community since the restriction might be applied from their side.

You may want to review [this question](http://stackoverflow.com/questions/14987496/background-color-not-showing-in-print-preview) for a quick fix.
