### ISSUE TITLE
Enhacncement: Add Select2

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#306]
[Select2](http://select2.github.io) is one of the popular web design components with a lot of useful functionality for selecting and tagging. It would be good to see it as part of AdminLTE.

**Comment by scottscreations** [comment]
i've been using this in my stuff, the select2 where you can swap between two select lists is the best.

**Comment by YasserHassan** [comment]
@scottscreations what did you mean by "swap between two select lists"?

**Comment by scottscreations** [comment]
@YasserHassan doh, i thought select2 was doing this but i just looked at my code, its multi-select found here: http://loudev.com/

**Comment by lenamtl** [comment]
Select2 can do the same as loudev but the look is different.
Select2 is the best script for selection and you can make group which is a plus, I have tested several scripts.

**Comment by almasaeed2010** [comment]
Sold on the idea. However I am not sure if I will implement it in the premium version or the open source one. Honestly, customizing the look of this script has proved to be a pain in the butt when I tried to do it before.

**Comment by kressly** [comment]
Select2 is VERY nice. However I have also faced some challenges in adding Images to it directly from the json. For example I wanted to use it to make a search and contact of person like it is done on the facebook search bar where you search for  friends and select them so that u can contact them. Adding images from my json (profile picture) has been a great challenge bcose it was not working on some browsers. Aside of that Select2 is really awesome .

**Comment by YasserHassan** [comment]
@almasaeed2010 I believe Select2 is ready out of the box for integration in AdminLTE. I recommend going for version 4, it is still pre-release but it's the future of Select2. The append and prepend addon states might need consideration though.

**Comment by almasaeed2010** [comment]
I saw the release candidate. It should be easier to customize but it isn't ready for AdminLTE. The field size does not match the rest of the input elements and the hover, active and focus states do not match either. Putting a select2 element with other AdminLTE form elements would look odd. I want to try my best to keep all the elements consistent with each other.

**Comment by fschaeffer** [comment]
@almasaeed2010 are you working on the premium version and will it be compatible in terms of source code? I'm very interested in supprting your work and would love to obtain a licence, especially when you are about to add more and more enterprice ready widgets.

I recently stumbeld over http://admindesigns.com/framework/dashboard.html which mimics the look and feel of AdminLTE but has a different html structure...

I am just working on a project which uses AdminLTE and would switch to the premium version if the structure remains the same...

**Comment by almasaeed2010** [comment]
Hello @fschaeffer I am currently working on both v2.1.0 and the premium version. The premium version will be an extension to AdminLTE. It is designed so that it integrates with the open source version as easily as possible. 

Regrading the template you linked to, it is based bootstrap as many other templates. Honestly, most of admin templates look similar and most have distinguishing features appealing to different tastes. AdminLTE is special since its base code is open source and has a great community support, which also might appeal to a different base of developers.

To clarify about the premium version, it would require little to no work to enable all of the new features. This implies the structure would not change at all. You will only have to include the new files (as needed) on top of the originals.

Thanks!

**Comment by fschaeffer** [comment]
Great, then I am looking forward to all the stuff that might come to both the free and the premium version, like the already good looking right sidebar which opens up great possibilities. Thanks a lot for the excellent work.

**Comment by almasaeed2010** [comment]
Integration is on progress. The first release of the premium collection will be around 5th of May.

**Comment by YasserHassan** [comment]
@almasaeed2010 I suggest you pay attention to Select2 in input groups both as making it an addon to other elements, and making other element addon to it, in append and prepend situations. This is an area where Select2 has no official style and handling this in your template would be a plus.

**Comment by Karmalakas** [comment]
I'm using latest AdminLTE (2.1.5) and Select2 (4.0.0)
Single select input works perfectly, but multiple select makes a lot of mess :/

**Comment by almasaeed2010** [comment]
I am adding Select2 to AdminLTE now. I will publish the functionality first then add the styling as necessary.

@Karmalakas thanks for letting us know. I'll test that and get back to you.
