### ISSUE TITLE
sidebar savestate?

### ISSUE THREAD

**Issue by t0n1zz** [almasaeed2010/AdminLTE#315]
Hi,
i wondering is there a way to make like if i hide sidebar, then when i navigate or reload the page, it will stay hidden and otherwise if the sidebar visible then it will stay visible until i click hamburger menu again to hide it and so on? since this template will always show page with sidebar visible

**Comment by YasserHassan** [comment]
This would be a good feature as persisting the UI state is required in most - if not all - of such web applications.

**Comment by almasaeed2010** [comment]
Hello,
Although this might sound like a front-end job but it isn't. This should be implement as a back-end mechanism. This is because when the user loads a new page, the default setting will be applied and javascript will deal with the saved state after the page loads. Thus, causing unwanted transitions and animations (i.e., the sidebar would appear in its regular state for a moment before javascript applies the collapsed mode). This could be a front-end job if we were using Ajax or AngularJS since the only change is in the content page not the sidebar nor the navbar.

**Comment by YasserHassan** [comment]
I agree with you on that undesired effect for HTML elements sent to the browser and the sidebar is one of them. It could be an option though for jQuery plugins initiated in the browser.

**Comment by almasaeed2010** [comment]
I am afraid I don't understand what you mean. Could you clarify please?

**Comment by YasserHassan** [comment]
What I meant is that trying to hide the sidebar on the client side will have the effect you mentioned; with each page load, you'd see the sidebar fully expanded first, then it collapses. So yes you better detect and persist its state on the server, not in the browser.

However, the status of jQuery components such as DataTables could be persisted on the client side because they are initialized inside the browser. This could result in a better user experience.

**Comment by t0n1zz** [comment]
yea i get that idea from datatables savestate feature and i loved it, i don't need to do any complicated thing to make sure i will back to the same table page when i submit something within the table

and also i think it will be great if when sidebar collapsed it's not entirely gone but only collapsed to the point where sidebar only show icons for each menu.... but it just a personal taste hahahahaha....

**Comment by almasaeed2010** [comment]
I understand your point and it is appealing to implement. However this is a bit of the template's scope and will consume time and effort that I don't possess. Thanks for the suggestion. Please keep it up!
