### ISSUE TITLE
WebSite Loading Issue

### ISSUE THREAD

**Issue by ArunJain** [almasaeed2010/AdminLTE#353]
Hi,

Thanks for a very good responsive template , i have downloaded and running it in local machine it generally takes 25 secs to load each time on my local machine can any one suggest , how to get started and resolve this issue thanks in advance

**Comment by almasaeed2010** [comment]
Hello,

I'd remove the font dependency by removing the first line in the AdminLTE.css file and try again.
This line: 
```less
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);
```

**Comment by almasaeed2010** [comment]
Which page is causing this issue? Or is it all pages?

**Comment by ArunJain** [comment]
After Downloading the template i opened the index.html page it normally takes like 22 secs to load each time on the browser and tried to open starter.html page also i faced the same issue.
Please help me out in this thanks in advance

**Comment by almasaeed2010** [comment]
To reduce the page load you can do some or all of the following:
1- Download font-awesome and ionicons and use them within your template instead of using a CDN.
2- Remove the font as I suggested in the first post.
3- If you are not using ionicons or font-awesome, you may remove them completely.

I hope this helps. I tested the template on a 20mbps and 8mbps internet connection and it didn't take too long. How are you testing your pages? Is there a specific tool you are using?
