### ISSUE TITLE
Datatables with Searchbox on top of each column

### ISSUE THREAD

**Issue by jdriesen** [almasaeed2010/AdminLTE#358]
Hi,

Great work and constantly improving. Love it !
I guess, for a lot of devs, it would be a great idea to implement (on datatables)
- column searching (filtering): i.e. a searchbox on top of each column
- an example of loading a huge amount of records (via JSON and ServerSide scripting.

Or maybe smb already has implemented this ?

PS.: Is there a reason why you didn't upgrade to datatables v1.10.x yet ?)
(x=6 at this moment of writing)

Thanks in advance for your reply,

Johnny

**Comment by almasaeed2010** [comment]
Hi Johnny,

The datatables feature you are requesting should be placed in their repository. I am honestly not very familiar with their development plans or how they handle suggestions.

I will update the version as soon as I get a chance. Thank you for reporting this!

**Comment by YasserHassan** [comment]
@almasaeed2010, @jdriesen, I'm afraid such requests would not add value to AdminLTE because this is more of a development issue than a templating one. Examples of the requested features should be available on the plugin website and adding them to AdminLTE would not add any "templating" value to it unless there's a conflict between them that needs fixing, not to mention that the time spent on fulfilling development issues would better be directed to "templating" ones. I prefer that @almasaeed2010 differentiates both types and focus on the templating side.

@jdriesen this reply is not meant specifically to your issue here but meant generally for this type of requests to raise the point as I keep seeing similar issues from other users too.

**Comment by jdriesen** [comment]
@YasserHassan : Thanks for your quick reply.
I perfectly understand your point.

(though, beside my questions, I still think it's worth upgrading to v1.10.6 of Datatables... :)
Kind regards,

Johnny

**Comment by YasserHassan** [comment]
@jdriesen I agree. Upgrading in general is good especially if automated as it ensures an acceptable level of compatibility between the template and the new plugins versions.

**Comment by almasaeed2010** [comment]
Upgraded to 1.10.6 and added extensions. Thanks!

**Comment by jdriesen** [comment]
Hi, @almasaeed2010 

Just for your information ...
I just grabbed your latest version via bower ... it seems that v. 1.9.4 of jquery.dataTables.js is still used.
As a double-check, I've download your ZIP file. That one has to latest version of jquery.dataTables.js (1.10.6)

I didn't check the other plugin versions...

Regards,

Johnny

**Comment by almasaeed2010** [comment]
@jdriesen the update was made to the master repo. The bower version won't be affected until the template has been fully tested on all supported browsers and a production increment has been released. Hopefully, we will soon see all updates from 2.0.x to 2.1.0 available in a production release. 
Thanks.
