### ISSUE TITLE
Sidebar + Fixed + Resize = Bug at the bottom

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#373]
Hello!

In the 2.1.0-beta, the following steps leads to a missing area at the sidebar's bottom:

1: Load the dashboard in a maximed window.
2: Click on the "Fixed" layout configuration.
3: Resize the window to a resolution like a smartphone.
4: Restore to the maximed state.
5: Look at the bottom of the sidebar. Something around 50px went missing.

![sidebar with fixed layout](https://cloud.githubusercontent.com/assets/12160864/7382553/c734f120-ede6-11e4-9cb7-9ca7b467143c.jpg)

The stable release does not have this problem.

Browser used: Chrome 42

**Comment by almasaeed2010** [comment]
Hello,

The issue is caused by Slimscroll, which apparently is not being removed completed when deselecting the fixed layout. This shouldn't be an issue in production since the demo menu should not be available to the end user. Nonetheless, I will look into it since I know what is causing the issue.

**Comment by rafael-renan-pacheco** [comment]
Hello Abdullah!

This issue also exists using the starter page, which will be available to the end user.

I first discovered this problem by adding itens to the starter page sidebar menu, and then I did the same steps in the demo menu to reproduce the problem and open this issue.

Best regards.

**Comment by almasaeed2010** [comment]
The starter template does not have the demo menu (the right sidebar demo config section). The ```starter.html``` which can be accessed after downloading the package, contains the actual starter template. You can take a look here for an example https://almsaeedstudio.com/themes/AdminLTE-dev/starter.html. I don't mean to say that this isn't an important issue but I'd like to point out that the ```demo.js``` file should not be included in your final product because it is unstable, untested and inconsistent (it can change without prior notice).

**Comment by rafael-renan-pacheco** [comment]
Hello!

But I am using the starter.html without the demo menu. I just set the fixed layout hardcoding the starter.html page, like adding the class "fixed" to the body tag, and enabling slimscroll, since I'm using fixed layout.

I opened this issue using the demo as example so you could reproduce the problem with ease.

Best regards.

**Comment by almasaeed2010** [comment]
Ok. Sorry for the misunderstanding. I guess the screenshot got me a bit confused. Currently I am working on issues #370 and #377, which have more significant errors. Once I am done with them, I will try to figure out what's causing this issue. Thank you for your patience!

**Comment by almasaeed2010** [comment]
I am not sure what is causing the issue. Apparently resizing the window resolves it. But since we can still scroll the sidebar even with the missing part and make all elements visible, then this isn't a big deal. In real life, I don't think users will purposely resize the window from that much. In the case of a tablet, this issue doesn't occur on iPad 2 when transforming from landscape to portrait and vice versa. If I am mistaken, please correct me. Thanks.

**Comment by rafael-renan-pacheco** [comment]
Hello Abdullah!

You are right, this is a very particular and rare bug to happen in real life. Even if the user does resize the window that much to fire the bug, it may even not notice the problem.

I thought that since the stable release don't have this problem, solve this one could be easy. But if it isn't, you can set this as low priority or close the issue.

Best regards,
Pacheco.

**Comment by almasaeed2010** [comment]
I am gonna have to let this be for now until I get the time to look into it. Currently I am concerned about releasing the new features as soon as possible. Thanks for the contribution!
