### ISSUE TITLE
Scroll Bar problem

### ISSUE THREAD

**Issue by athenaneo** [almasaeed2010/AdminLTE#375]
Hello!

In the 2.0.3, the following steps leads to block scrolling  sidebar's

1: Load the dashboard in a maximed window.
2: Click on the "Fixed" layout configuration.
3: then scroll with keybord up and down arrow key ,its not scrolling

**Comment by almasaeed2010** [comment]
Hello,

Which browser are you using? On chrome this is not an issue.

**Comment by rafael-renan-pacheco** [comment]
Hello!

Using keyboard up/down scrolls the main content up/down, not the sidebard if fixed layout is activated. I think that is the issue athenaneo reported.

At https://almsaeedstudio.com/themes/AdminLTE-dev/index2.html the problem can be reproduced.

I'm using Chrome 42.

Best regards.

**Comment by almasaeed2010** [comment]
@rafael-renan-pacheco that's correct. This would be an issue caused by the SlimScroll plugin. I think it is time for an upgrade since SlimScroll is causing multiple issues other than this. I will look into it and see if I can find a better plugin that serves a similar purpose but better. Thanks!

**Comment by athenaneo** [comment]
thank you for helping me, Kindly requested you to upgrade the plugin and inform us.

**Comment by almasaeed2010** [comment]
Changing the plugin would be a problem since many users already integrated it into their version of AdminLTE. We follow the rules of semantic versioning, which does not allow for major changes unless a major release has been issued. In our case, this would only be possible if we release AdminLTE 3.0, which we are a long way from. I appreciate that you have reported this issue, and apologize for not being able to help you any further.
