### ISSUE TITLE
Active menu de active when i collapse parent ment menu 

### ISSUE THREAD

**Issue by rashed-zaman** [almasaeed2010/AdminLTE#380]
![adminlte preview almsaeed studio](https://cloud.githubusercontent.com/assets/8373115/7421133/ddf5af1c-efa3-11e4-82ed-dea871e0c35c.png)

**Comment by rashed-zaman** [comment]
Here Dashboard v2 is active but when I collapse dashboard and again re open Dashboard v2 is De-active but i am still on same page. how i fixed this issue ??

**Comment by almasaeed2010** [comment]
This is related to the app.js. I can't currently fix it because it will require modification to the main script and thus enforcing html markup change on the users. Therefore, breaking semantic versioning rules.

You can modify the script to fit your needs. In particular, you need to modify the ```$.AdminLTE.pushMenu.activate``` function.

**Comment by rashed-zaman** [comment]
please guide me how i fixed it $.AdminLTE.pushMenu.activate function.

where I found $.AdminLTE.pushMenu.activate function in app.js. ??

**Comment by rashed-zaman** [comment]
I believe its related 
/* Tree()
 * ======
 * Converts the sidebar into a multilevel
 * tree view menu.
 *
 * @type Function
 * @Usage: $.AdminLTE.tree('.sidebar')
 */
$.AdminLTE.tree = function (menu) {

**Comment by rashed-zaman** [comment]
I believe its related 
/* Tree()
 * ======
 * Converts the sidebar into a multilevel
 * tree view menu.
 *
 * @type Function
 * @Usage: $.AdminLTE.tree('.sidebar')
 */
$.AdminLTE.tree = function (menu) {
