### ISSUE TITLE
Menu overflow

### ISSUE THREAD

**Issue by digicp** [almasaeed2010/AdminLTE#392]
Is this a JS or CSS error? This is only on mobile format.

![adminlte-menu-bug-mobile](https://cloud.githubusercontent.com/assets/9464048/7446486/8f94696a-f1da-11e4-9cc3-42d22cf0610a.png)

**Comment by almasaeed2010** [comment]
If this code works then it is css. Try adding this to your css and let me know if it works:
```css
.left-side {
  z-index: 840;
}
```

**Comment by digicp** [comment]
it doesn't work. I also tried:

.left-side {
  z-index: 1;
}

**Comment by almasaeed2010** [comment]
Without access to the dashboard, I am not sure what the error could be. Apparently, you are using and old version of AdminLTE. Have you considered upgrading?

**Comment by digicp** [comment]
When I will upgrade, what kind of files do I need to replace? Only the css and JS, or do I also need to re-create all the pages?

**Comment by almasaeed2010** [comment]
There are a few changes to the HTML but they are minor changes and easily replaced. Here is the [upgrade guide](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade). Please upgrade to a stable production version such as 2.0.5 instead of using any alpha or beta versions. You can download the latest releases from [here](https://github.com/almasaeed2010/AdminLTE/releases).
