### ISSUE TITLE
Make A-element inside "treeview" class function like a link.

### ISSUE THREAD

**Issue by halvors** [almasaeed2010/AdminLTE#440]
Make A-element inside "treeview" class function like a link.

Also being able to click the element that expands the treeview.

**Comment by almasaeed2010** [comment]
I am not sure I get the issue. Please elaborate and provide a solid example for me to help you. Thanks!

**Comment by chuygb** [comment]
When you have a tree on the side bar, you remove links on parents of branches, so clicking them just opens the children, but soemtimes we want to have parents behave as filters, so click on parent opens children and refreshes filtered view that includes all children
then clicking on children, filters again for that element

Since I use label counts, probably clicking anywhere just opens, and on label filters,
any way is OK, I tried listenign on the label click and did not work

**Comment by almasaeed2010** [comment]
You may need to add ```event.stopPropagation()``` to make it work. Otherwise, I am not sure how I can help.

**Comment by chuygb** [comment]
to the sidebar?
today i put a lin on the ref, of an and it gets removed, so an example on when to ad an o'clock to those nodes, or the stop propagation, could help
*On my requirement, I still need the click to open child rows, all I need is then to refresh the body of the document with the results  of the top item

**Comment by chuygb** [comment]
I believe I have the solution, on  $.AdminLTE.tree = function (menu) { 
on the app.js file, executing the link if not #, after the actual open/close can do it
Will post solution when tested, currently on other urgencies
Probably trigger link only when opening, not on close, still undecided

**Comment by harryPL** [comment]
I've got the same problem. The one element of the tree menu is a link  and I would like it to open the link when I click on it and expand the submenu only when I click on the the icon that indicates that it has some descendants. Unfortunately I can find a way to do this.

**Comment by fschaeffer** [comment]
also interested in such a function, I'm using the navigation as product hierarchy and would also like to be able to attach a link on parent nodes instead of only opening the child nodes ...

**Comment by harryPL** [comment]
@almasaeed2010 any ideas on how to achieve it?

**Comment by chuygb** [comment]
I have an idea how to achieve, but haven't had the time to go trough it
-1- Since our link gets overridden on parent branches, we need to add a tag to keep it safe
some thing like data-parent-ref=".........."
-2- We need to decide who it should work
..currently.. click open/closes tree
option a: Do the same as now and then execute link (my option) since for me tree is a folder hierarchy and I refresh body of page
option b: add a font-awesome icon so that simple click just upen/closes tree, but icon executes the link

-3- the place to act on click is on file dist/app.js line apron 379

    $("li a", $(menu)).on('click', function (e) {
      //Get the clicked link and the next element
      var $this = $(this);
      var checkElement = $this.next();

      //Check if the next element is a menu and is visible
      if ((checkElement.is('.treeview-menu')) && (checkElement.is(':visible'))) {
        //Close the menu
        checkElement.slideUp('normal', function () {
          checkElement.removeClass('menu-open');
          //Fix the layout in case the sidebar stretches over the height of the window
          //_this.layout.fix();
        });
        checkElement.parent("li").removeClass("active");
      }
      //If the menu is not visible
      else if ((checkElement.is('.treeview-menu')) && (!checkElement.is(':visible'))) {
        //Get the parent menu
        var parent = $this.parents('ul').first();
        //Close all open menus within the parent
        var ul = parent.find('ul:visible').slideUp('normal');
        //Remove the menu-open class from the parent
        ul.removeClass('menu-open');
        //Get the parent li
        var parent_li = $this.parent("li");

        //Open the target menu and add the menu-open class
        checkElement.slideDown('normal', function () {
          //Add the class active to the parent li
          checkElement.addClass('menu-open');
          parent.find('li.active').removeClass('active');
          parent_li.addClass('active');
          //Fix the layout in case the sidebar stretches over the height of the window
          _this.layout.fix();
        });
      }
      //if this isn't a link, prevent the page from being redirected
      if (checkElement.is('.treeview-menu')) {
        e.preventDefault();
      }
    });
  };

**Comment by fschaeffer** [comment]
I'd also would expect option 2b: 
- click on a node without href would open the next level
- clicking on a link with href would open the target (it then would be the task of the target to display the navigation expanded anyways)
- clicking on the arrow would allow to expand the next level without opening the target...

**Comment by chuygb** [comment]
Looking int how to decide what to do onClick
I have traced the following
by adding a console log on the .tree on click event handler (minimized)
$.AdminLTE.tree=function(a){var b=this;$("li a",$(a)).on("click",function(a){var c=$(this),d=c.next();console.log(event.target);<----------------------
----on console log on safari------------------------
Click on header  shows: 
    [Log] <span>​Multilevel​</span>​ (app.min.js, line 13)
Click on header icon (arrow) shows: 
    [Log] <i class=​"fa fa-share">​</i>​ (app.min.js, line 13)
Click on header icon (angle icon) shows:
    [Log] <i class=​"fa fa-angle-left pull-right">​</i>​ (app.min.js, line 13)
Click on a branch shows:
    [Log] <a href=​"#">​…​</a>​ (app.min.js, line 13)
Click on a branch icon shows:
   [Log] <i class=​"fa fa-circle-o">​</i>​ (app.min.js, line 13)
Click on a branch icon (angle icon) shows:
    [Log] <i class=​"fa fa-angle-left pull-right">​</i>​ (app.min.js, line 13)
....fa-angle-left  toggles depending on state of branch...............



So i believe by just distinguishing what element got clicked the behaviour can be decided
I actually show a banner with items count on each line so that is an additional element to use

my behaviour 
....everything works as default
....if the branch has a banner then after default, I refresh body of page with new records matching branch
....Some of my queries on header branches can be slow to respond so by default user opens until the detail leven he wishes and can click on a leaf and get his results, BUT clicking on a record count will show aggregated results

Will share my code when done but that sprint comes in 2 weeks

**Comment by fschaeffer** [comment]
Would be nice to work like https://github.com/jonmiles/bootstrap-treeview ....

**Comment by n3storm** [comment]
I support @fschaeffer suggestion.

My issue is to make each entry in the menu have some more functionality than only collapsing tree:

<parent <a createchild><a switch>>



Hope it helps.

**Comment by imhubertj** [comment]
hi guys, just like to check if there is any updates on this function yet? I like to make the parent tree branch clickable to a href page and at the same time not remove the tree function on the sidebar.

any ideas?

**Comment by chuygb** [comment]
I started coding this week among other items, probably in a week i can provide an update

Jesús A. Guzmán Bremer
Corporate Development Manager
Qualfon, Mexico
 
Office: (81) 8150 3100 ext 27007
Mobile: +52 (81) 1251-2004
Skype: chuyeiris 
Email: jguzman@qualfon.com <mailto:jguzman@qualfon.com>
www.qualfon.com <http://www.qualfon.com/>
 
CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended only for the person or entity to which it is addressed and may contain confidential and /or privileged material. Any review, use, disclosure or distribution of such confidential information without the written authorization of Qualfon is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. By receiving this e-mail you acknowledge that any breach by you and/or your representatives of the above provisions may entitle Qualfon to seek for damages.

AVISO DE CONFIDENCIALIDAD: Este correo electrónico, incluyendo en su caso, los archivos adjuntos al mismo, pueden contener información de carácter confidencial y/o privilegiada, y se envían a la atención única y exclusivamente de la persona y/o entidad a quien va dirigido. La copia, revisión, uso, revelación y/o distribución de dicha información confidencial sin la autorización por escrito de Qualfon está prohibida. Si usted no es el destinatario a quien se dirige el presente correo, favor de contactar al remitente respondiendo al presente correo y eliminar el correo original incluyendo sus archivos, asi como cualesquiera copia del mismo. Mediante la recepción del presente correo usted reconoce y acepta que en caso de incumplimiento de su parte y/o de sus representantes a los términos antes mencionados, Qualfon tendrá derecho a los daños y perjuicios que esto le cause

**Comment by harryPL** [comment]
@chuygb what's the status? :)

**Comment by kticka** [comment]
I'v added one simple 'if' on app.min.js. It works on adminlte2.
When link is url, it just follows it, when its '#', then it's just expant menu.
~~~
$.AdminLTE.tree = function(a) {
	var b = this,
  c = $.AdminLTE.options.animationSpeed;
	$(document).on("click", a + " li a", function(a) {
    var d = $(this);
    var e;
    if (d.attr('href') == '#') {
      e = d.next();
      if (e.is(".treeview-menu") && e.is(":visible")) e.slideUp(c, function() {
        e.removeClass("menu-open")
      }), e.parent("li").removeClass("active");
      else if (e.is(".treeview-menu") && !e.is(":visible")) {
     		var f = d.parents("ul").first(),
        g = f.find("ul:visible").slideUp(c);
        g.removeClass("menu-open");
        var h = d.parent("li");
        e.slideDown(c, function() {
          e.addClass("menu-open"), f.find("li.active").removeClass("active"), h.addClass("active"), b.layout.fix()
        })
      }
      e.is(".treeview-menu") && a.preventDefault()
   	}
	})
}
~~~

**Comment by MetaCrawler** [comment]
I'm also interested in this option. 
The solution suggested @kticka worked for me as a quick fix... 
But it would be very nice to have this already included without digging and modifying the core files.

**Comment by almasaeed2010** [comment]
@MetaCrawler 
Add the suggestion to the AdminLTE 3.0 announcement #710.

**Comment by Ruth-Cantoni** [comment]
Are there any news about this subject?
