### ISSUE TITLE
Any plans for AdminLTE run fully locally?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#448]
Hi! After a little research in the Issues list, I found that some users requested, or would like to see, AdminLTE run on localhost, without internet. 

I found this same problem trying to run AdminLTE on a environment filled with firewall rules, which blocked the download of the following plugins/css/extensions:

> https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
> https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
> http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js
> https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js

Is there any plan about running AdminLTE without downloading external dependencies?

Download them all manually and change AdminLTE.css is a workaround, but when an AdminLTE update comes, it will override these changes.

These are the issues I found about this topic: #290 #48 #301 #162 #133

Best regards,
Rafael.

**Comment by sniper7kills** [comment]
Rafael,
Just my two cents; But I would agree that the bower.json file should be updated to include the dependency's; Beyond that the files included should only be used as templates for coding your own pages.

As such; the links to the CDN are simply a way for the author to minimize the package size and allow 99% of users who don't have firewall issues to instantly view the examples. And to include those dependency's in the package itself would be overkill; especially for people that use multiple packages. Image if every package owner included all required dependency's in their package; you would end up with tens of copies of jquery.min.js

Running:

    bower install raphael moment ionicons font-awesome jquery jquery-ui adminlte -S
    cp bower_components/adminlte/pages ./
    cp bower_components/adminlte/*.html ./

Should get you started; From there yes you'll have to replace the CDN links but it won't break on update unless the HTML gets changed. Running bower update will then allow you update all the packages and dependency's without downloading everything multiple times just because one package got updated.

To replace the CDN links look at using sed. The example below won't work past the index page unless you are running a local webserver; but should give you the idea.

    sed 's,https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css,./bower_components/font-awesome/css/font-awesome.min.css,g'
    sed 's,https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css,./bower_components/ionicons/css/ionicons.min.css,g'

**Comment by rafael-renan-pacheco** [comment]
Hello Will!

Using bower and sed as you said could solve this problem, I'll try that.

I hope your contribution can be made into a future AdminLTE release, so those who need a complete offline instalation can use an out-of-the-box solution.

Thanks for the reply,
Rafael.
