### ISSUE TITLE
How best to use other pages without duplicating the whole layout

### ISSUE THREAD

**Issue by dschueler** [almasaeed2010/AdminLTE#464]
I love this theme but its not clear to me how to maintain the overall look of the sidebars and navigation etc. and be able to show a different content wrapper section. I want to keep only one main navigation page at the moment. How can I replace "content wrapper A" with "Content Wrapper B" all within the same home page?

**Comment by rafael-renan-pacheco** [comment]
In MVC, the whole page is loaded for every request, this is a very common concept these days, since browsers have a good performance to handle this task.

For example, a lot of MVC PHP Frameworks shows the whole page for each request, without reloading just a content wrapper.

If you do need to load/reload just some section of your app, then you are looking for Ajax and maybe AngularJS.

AdminLTE and PHP Frameworks won't do this, since they are MVC oriented, but you are free to Ajax it or AngularJS it.

**Comment by almasaeed2010** [comment]
@rafael-renan-pacheco is right. 

It seems like you are looking for an Ajax approach. Which language are you using for back-end development? Most languages would allow you to split the layout into files such as header.php, footer.php and sidebar.php. Each of which only contains the necessary code for the layout. Some template engines such as Blade would allow you to do even better than that by defining internal content section within one file.

**Comment by chuygb** [comment]
I had the same question, and there are 2 good choices
-Create a single page app, where you keep using the same loaded resources, and you kill the contents, to display new. Simple, Bookmarkable apps are obtained with a pug in that helps change conent and manipulate the location without refreshing, your app becomes all ajax
-The second you have module that is able write the basic frame of the page, and you call this in js just after loading the page. So your pages in html have a div that will end up in the contents, and after filling in your master page, you just move and show the actual body of the page
