### ISSUE TITLE
Skin: "black is white"

### ISSUE THREAD

**Issue by schmunk42** [almasaeed2010/AdminLTE#465]
The black skin has a bright white header, I'd have expected a black one.
Could you change that to black and add a white ... and a gray one.

**Comment by suvjunmd** [comment]
+1

**Comment by almasaeed2010** [comment]
:-z 
You are right. The name is kind of confusing. I, however, can't change it right now since it directly affects users who might update regularly. Once I start working on 2.2.0 I will change that. I am not sure about adding more skins at this time. But it is for sure something to think about. Thank you!

**Comment by drmcclelland** [comment]
+1 from me too!

Also, if there is a way to specify that a skin's sidebar and header are the SME color, that would be ideal for me.
