### ISSUE TITLE
Inegrate with codelgniter

### ISSUE THREAD

**Issue by bilouStrike** [almasaeed2010/AdminLTE#478]
Salam ,
Why happen this in Chrome,Opera browser ,  the header down ,  whene i integrate the template AdminLTE  with php codelgniter ? thanks
![impr](https://cloud.githubusercontent.com/assets/12693924/7910175/511d15e8-084a-11e5-97c7-b39f88e51ca1.jpg)

**Comment by YasserHassan** [comment]
@bilouStrike if this issue appears only after your integration then your implementation does not reproduce proper AdminLTE HTML (structure and/or associated CSS classes). You need to compare the structure (DOM) resulting from your integration with that of the original template to identify the discrepancies causing this issue.

**Comment by bilouStrike** [comment]
@YasserHassan thanks, but i do this , it work good in firefox, the problem is only Chrom and Opera

**Comment by almasaeed2010** [comment]
Please provide any errors that appear in the console if any exists

**Comment by rafael-renan-pacheco** [comment]
This is usually caused by php files with UTF8+BOM encoding.

Check if the generated HTML have "blank" spaces before doctype. These blank spaces generated by BOM can cause some padding issues in bootstrap. Also those "blank" spaces can appear between tags, which will also crash your layout. I wrote "blank" because they are not actually blank spaces, but chrome html viewer render them as invisible spaces.

If this is the case in your php files, open them all in your favorite text editor, and encode them as UTF8+Without BOM.

Best regards.

**Comment by bilouStrike** [comment]
@rafael-renan-pacheco, i change my file to UTF8+Without BOM and  it's working good..
thanks very much.
