### ISSUE TITLE
Use font-awesome atop text input elements

### ISSUE THREAD

**Issue by masteradhoc** [almasaeed2010/AdminLTE#479]
Hi @almasaeed2010 

Why have you used glyphiconincons at the login and registerpage?
I wanted to change them to fontawesome but actually getting some graphical issues then.

Tried to change this:
<span class="glyphicon glyphicon-lock form-control-feedback"></span>
into:
<span class="fa fa-lock form-control-feedback"></span>

The attached picture shows the emailpart (made with fa) and the passwordpart (you have made with glyphicon) Thanks
![iconfail](https://cloud.githubusercontent.com/assets/6242098/7913154/b8310244-086d-11e5-92ca-d68c539be13d.png)

**Comment by almasaeed2010** [comment]
I haven't added support to font-awesome for icons yet. Thanks for reminding me. I'll add support when I get a chance.

**Comment by masteradhoc** [comment]
That would be great for the next Version, thanks!

**Comment by fschaeffer** [comment]
+1 would be ...awesome... to include support for FA, as we then could remove glyphicons and ionicons to only have one icon resource on the page (page download size counts in mobile scenarios...)

**Comment by masteradhoc** [comment]
+1 same opinion :)

**Comment by fschaeffer** [comment]
As a quick fix one could add 
```
.form-control-feedback.fa {
    line-height: 34px;
}
```
but this will not work with smaller or larger input-boxes (input-lg, input-sm).

I just digged into the code and found that the issue comes due inheritance in Bootstrap. In the bootstrap.css the glyphicons span container is defined as line-height: 1, later on the form-control-feedback sets line-height to 34px / 46px for large input boxes.

As Font Awesome is loaded after BS their line-height: 1 keeps precedence and sets the line-height back to 1.

I found no way to override this without passing some !important to form-control-feedback line-height, which then again has to be done for all input-sizes.

As I'm using less and AdminLTE includes the bootstrap variables.less the easiest and correct solution for me was to reuse their @input-height-base / @input-height-large / @input-height-small and add this to my own less file (which of course includes the AdminLTE.less).

```
// Feedback icon
.form-control-feedback.fa {
    line-height: @input-height-base;
}

.input-lg + .form-control-feedback.fa,
.input-group-lg + .form-control-feedback.fa,
.form-group-lg .form-control + .form-control-feedback.fa {
  line-height: @input-height-large;
}
.input-sm + .form-control-feedback.fa,
.input-group-sm + .form-control-feedback.fa,
.form-group-sm .form-control + .form-control-feedback.fa {
  line-height: @input-height-small;
}
```
This solves all problems for me. If anybody has interest I could prepare a PR for AdminLTE less / css.
