### ISSUE TITLE
Main header example in documentation breaks at page width of 757px

### ISSUE THREAD

**Issue by suvjunmd** [almasaeed2010/AdminLTE#494]
Internet Explorer 11 on Windows 8.1
![b1](https://cloud.githubusercontent.com/assets/11020536/8025170/9e45ad44-0d54-11e5-8a9f-30095464439c.png)

Chrome 43 on Windows 8.1
![b2](https://cloud.githubusercontent.com/assets/11020536/8025172/a8b262c2-0d54-11e5-9b8f-c3912737c94d.png)
![b3](https://cloud.githubusercontent.com/assets/11020536/8025174/ab194da0-0d54-11e5-815f-e427317694ae.png)

**Comment by almasaeed2010** [comment]
The example in the documentation lessens the width of the screen by 230 pixels, which is the size of the sidebar. Thus, causing the overflow problem. In reality, this problem would not occur unless you add too many icons and links in the navbar. I didn't fix the issue although I was aware of it because it doesn't make sense to fix something that's not broken. 

Thank you for sharing the issue.
