### ISSUE TITLE
Remove all !important directives from css/less files

### ISSUE THREAD

**Issue by bryanspears** [almasaeed2010/AdminLTE#499]
AdminLTE is a basis from which to build fantastic admin web interfaces. However, layering styles over it has some issues with a number of `!important` directives I've found.

**Comment by almasaeed2010** [comment]
Most of the rules that use ```!important``` are there to override Bootstrap components that otherwise would require a full path to the element. If all ```!important``` statements were removed, some elements would look and perhaps behave differently than what's intended. I am sure there are a few that are possibly not needed and are there by mistake, but most of them are required.

Thanks.

**Comment by bryanspears** [comment]
I understand why it was done, and how it works, but I'd much prefer verbose css paths to using `!important`. Using `!important` is a shortcut and every developer after you must also use `!important` to override affected styles. Defeats the purpose of having "cascading" styles, doesn't it? Any changes have to use a trump card to function.

**Comment by almasaeed2010** [comment]
I will look into this further with the next major release. 

Thanks.

**Comment by varblob** [comment]
+1 I've been using the admin lte stylesheet but am now considering dropping it for this reason.

**Comment by almasaeed2010** [comment]
Removed unnecessary !important statements and edited some to not use it. Background contextual classes have !important statements because they are needed in many cases to override default backgrounds. An example of that can be found in the timeline. Thanks.
