### ISSUE TITLE
Sidebar menu doesn't scroll

### ISSUE THREAD

**Issue by AndrewLag** [almasaeed2010/AdminLTE#528]
I noticed from mobile browser, that the left sidebar doesn't scroll when the .content's height is less high than the .sidebar-menu's height. That happens with fixed layout.

For example, check the blank page of the demo. How can it be solved? Is that a bug?
Thanks for your support.

**Comment by almasaeed2010** [comment]
Could you make sure that the slimscroll plugin has been loaded? If so and the issue still persists, please provide the type of device you are using.

Thanks.

**Comment by AndrewLag** [comment]
I use Google Chome from Samsung S4 mini.

Try it yourself from mobile
1) Go to blank page https://almsaeedstudio.com/themes/AdminLTE/pages/examples/blank.html
2) Open right sidebar
3) Activate "Fixed layout"
4) Close right sidebar
5) Open left sidebar and try to scroll.

Thank you.

**Comment by almasaeed2010** [comment]
Unfortunately, this could be a Slimscroll issue. The issue doesn't occur when not using the fixed layout. The SlimScroll repo doesn't seem responsive to issues so we decided to use a different plugin in the future. For the time being, you can use the regular layout instead of fixed or advise your visitors to use supported browsers. 

Thank you for reporting the issue and we apologize for the inconvenience.
