### ISSUE TITLE
A question for future consideration: Material design

### ISSUE THREAD

**Issue by ivantcholakov** [almasaeed2010/AdminLTE#539]
@almasaeed2010

What do you think about adopting the Material design concepts by Google in a future version of AdminLTE (probably Bootstrap 4 based)?

http://www.google.com/design/spec/material-design/
https://github.com/FezVrasta/bootstrap-material-design

**Comment by almasaeed2010** [comment]
Hi,

Material design would be perfect for a different project. I appreciate the suggestion but I don't think we will do that for AdminLTE. Perhaps the next open source template.

Thanks!

**Comment by YasserHassan** [comment]
Material design includes many concepts that AdminLTE can benefit from. It does not need to be fully implemented, at least at once swap. If it proves to be a highly coveted feature by the AdminLTE community, why don't we start incorporating it on small doses over several releases till it reaches a full implementation.

Discussing another open source template actually concerns me as that could lead to a situation with two (or more) projects competing with each other on time and effort instead of one taking all the attention and evolves better. Also will lead to developers wanting something in a middle after comparing the two templates ending up with a feeling of frustration when they find it hard to have it in maintainable way.

If the benefit of another template is a different layout or features, it would probably be better to spend that effort in changing AdminLTE to be more dynamic by looking at it as a set of  configurable components that could be assembled using configuration files. That could be achieved by enhancing the structure (LESS/SASS, JS, HTML via templating). For example imagine treating the navbar, side bars, footer, ...etc each as an independent component and having a top level assembly template to layout and assemble those components together. It's not that simple as there's still JS and CSS but just to give the idea. That seems like a lot of work but I believe that approach would be more productive than starting a new open source template project.

**Comment by n3storm** [comment]
I would also prefer to see Material design not in AdminLTE. Thanks

**Comment by rafael-renan-pacheco** [comment]
> why don't we start incorporating it on small doses over several releases till it reaches a full implementation

:+1: Agreed! Could you tell us what would be the first step of this transformation? Material have several steps, what would be the first one to start with, without having a huge impact on the actual AdminLTE?

> Discussing another open source template actually concerns me as that could lead to a situation with two (or more) projects competing with each other on time and effort instead of one taking all the attention and evolves better

:+1: Agreed too!

**Comment by YasserHassan** [comment]
@rafael-renan-pacheco it could be something as simple as colors but without gaining acceptance and figuring how much effort will be put into it we can not put a realistic road map.

Material design is probably more relevant on mobile devices but then you'd rather develop a specialized mobile app (and have all the material design you want). I see the benefit of material design for AdminLTE highly questionable and I'm more in favor of dropping it.

**Comment by almasaeed2010** [comment]
I tried to use the library provided by @ivantcholakov to create a branch of AdminLTE that supports Material Design concepts. However, there are multiple incompatibilities that resulted in breaking the layout. It's still an option for future releases. I doubt we can implement it on small doses since the concept changes major design aspects of the template. If we take the route of implementing only some elements, the template will most likely lose consistency. It's either going all the way, or not at all. At least in my opinion. 

Thanks for the suggestion. I will for sure keep it in mind.

**Comment by jlamer** [comment]
There is also this bootstrap "style": http://bootswatch.com/paper/ which should be similiar to material design. If someone wants badly material design, he can still try to use it. I would concentrate on new features and addons support and only slightly adapt design to cope with new trends.

**Comment by ivantcholakov** [comment]
http://www.getmdl.io
https://github.com/google/material-design-lite

**Comment by DucThanhNguyen** [comment]
I've tried to add [Material Design](http://www.google.com/design/spec/material-design/) for AdminLTE using [Bootstrap Material Design](https://github.com/FezVrasta/bootstrap-material-design). It took me a few hours to combine the two. Of course there are still many things that need to work on, but i think it's a good start.
My repo: [MaterialAdminLTE](https://github.com/DucThanhNguyen/MaterialAdminLTE)
Demo: [https://ducthanhnguyen.github.io/MaterialAdminLTE](https://ducthanhnguyen.github.io/MaterialAdminLTE)

**Comment by gaving** [comment]
@DucThanhNguyen nice!

**Comment by ivantcholakov** [comment]
@DucThanhNguyen Wow, impressive!
I am in a process of migration of my software base beyond Bootstrap 3. Are you interested in [Semantic UI](http://semantic-ui.com)?

**Comment by DucThanhNguyen** [comment]
@ivantcholakov Yes, Sematic UI looks interesting. I'm using Bootstrap 3 for most of my web applications. I'm software programmer but interested in UI & UX

**Comment by acacha** [comment]
@ivantcholakov Amazing! Good job!
