### ISSUE TITLE
Suggestion: Using Google Charts

### ISSUE THREAD

**Issue by Leon-O** [almasaeed2010/AdminLTE#645]
It would be nice to see some Google charts, https://developers.google.com/chart/interactive/docs/gallery, with the themes of AdminLTE.

**Comment by almasaeed2010** [comment]
@Leon-O you can use any charts library with AdminLTE. I chose the few we have because of their simplicity and to provide an example. However, there are many awesome charts libraries out there like HighCharts, jqPlot and Google Charts. 

You can report any problems that may occur when integrating Google charts with AdminLTE here. Thanks for the suggestion!
