### ISSUE TITLE
fastclick is not working (300ms delay)

### ISSUE THREAD

**Issue by iamgoodbytes** [almasaeed2010/AdminLTE#688]
Hi! First of all I want to thank @almasaeed2010 for the fantastic template and for sharing it with us. 

I ran into an issue where fastclick isn't loading with a 300ms delay as a result. I've logged the issue with FastClick, but it's probably an issue with AdminLTE: https://github.com/ftlabs/fastclick/issues/409#issuecomment-141074229

You can try it out by going to adminLTE preview on an iphone and navigate through the menu. You'll notice a 300ms delay when clicking around menu items.

Any idea what can be the issue here?

**Comment by almasaeed2010** [comment]
I see the issue you are talking about. I've always doubted whether it was actually working or not. Could it be because we are attaching the Fastclick listener too soon? I am not sure I really understand how the script work at the moment but I remember it working better when I first implemented it. I think we need to reconsider using the script if it isn't doing what its supposed to. I will look into this further when I get a chance.

I apologize for the delay, too many school related projects at the time. I appreciate the compliments!

Thanks!

**Comment by iamgoodbytes** [comment]
Hi Abdullah! Thanks for taking the time to respond. My guess is indeed that the screen is being attached before the content is fully loaded. Fastclick itself works fine, I've used in in several other projects.
