### ISSUE TITLE
Datatable Excel, PDF and Print Buttons

### ISSUE THREAD

**Issue by netmas** [almasaeed2010/AdminLTE#692]
Hi, i think adminLTE is great and i'm looking forward to use it. But, i'm trying to use the excel, pdf and print capability of the datatable plugin. For some reasen when i'm capable of adding the buttons the table is not responsive anymore, and besides i can't see the table length control anymore. Is there way to provide that with adminLte?

**Comment by almasaeed2010** [comment]
Hello
Could you provide a link to the plugin you're suggesting?

I appreciate the suggestion!

**Comment by netmas** [comment]
Hello,

This is the link of the plugin.

https://www.datatables.net/

Thanks

2015-09-26 17:25 GMT-03:00 Abdullah Almsaeed <notifications@github.com>:

**Comment by jlamer** [comment]
How do you add buttons? You need to preserve .datatable class on table element and datatables should work without problems.

**Comment by MrLinDowsMac** [comment]
@netmas @almasaeed2010 Actually, this is the extension that you (and me) want: https://www.datatables.net/extensions/buttons/

**Comment by netmas** [comment]
Hello!! yes it is. But, i coundnt make it work. I've tried, and got the
buttons working but that disables the search box or the page number. Can
you give it a try? I tried with the html5 buttons there is another approach
with swf.

Thanks a lot



2015-10-06 15:50 GMT-03:00 Ian Nájar <notifications@github.com>:

**Comment by MrLinDowsMac** [comment]
I have my own DataTables with the sorting and search box included in another project. I tried to apply them in the code of `AdminLTE/pages/tables/data.html` examples, but didn't work. Apparently something is missing.
I Can't tell if the required extension is included because you are using a minified version of DataTables.

**Comment by MrLinDowsMac** [comment]
I've made it. Apparently you didn't include the extension in your build. You could get a custom build from here: https://www.datatables.net/download/
Don't forget to add pdfmake and JsZip as they suggest, otherwise HTML5 export won't work.
Finally, the I modify one of your examples, see my pull request:
https://github.com/almasaeed2010/AdminLTE/pull/721

**Comment by netmas** [comment]
Thanks a lot. I'll check it

**Comment by netmas** [comment]
Hi, i've been working with the buttons and i found two issues when working
with ajax loaded data.

1. The datatable looses responsivity
2. The excel, print and pdf buttons disappear

I've been trying to make work with deferRender option ... but it doesnt get
better

I found this article, and it seems that it doesnt have a solution

https://datatables.net/forums/discussion/25375/responsive-plugin-with-serverside-processing

Any ideas?

2015-10-06 23:04 GMT-03:00 Gonzalo Ortellado <
administracion.netmas@gmail.com>:

> Thanks a lot. I'll check it

**Comment by MrLinDowsMac** [comment]
Datatables have an extension for hiding columns, when the device width screen is two short, It sets a column with a (+) where it shows the values of the hidden columns. Maybe you should try to add that extension

**Comment by biaocy** [comment]
@netmas the excel button need jszip.js, pdf button need pdfmake.js, print button need buttons.print.js
