### ISSUE TITLE
Search  functionality on left menu

### ISSUE THREAD

**Issue by manis6062** [almasaeed2010/AdminLTE#696]
Search on left side bar is not working.It would be great if there's a functionality of live search.Thanking You

**Comment by almasaeed2010** [comment]
Hello,

Since this functionality hasn't been implemented yet, I strongly encourage you to add the feature yourself because it is simple and I currently don't have much time. Here is a tutorial on how to do it: http://www.jqueryscript.net/layout/Filterable-Tree-View-Plugin-with-jQuery-Tree-Filter.html

Thanks and sorry for the inconvenience!
