### ISSUE TITLE
asking about intergace

### ISSUE THREAD

**Issue by RoyTerrazas** [almasaeed2010/AdminLTE#726]
I have the following questions: I´m using version 2.3.0

1: How do I change the apperance of the text boxes from a square looking box to a rounded one?

2: Im using this
```html
<input type="text"  placeholder="IELTS" class="form-control span1" id="ielts" name="ielts"  maxlength="3" >
```
But the span1 command does not work, it doesnt change the size of the text, how do I change it?

3:  which class do I have to use in order to have a nicer en better appealing file component when using this?:
```html
<label for="exampleInputFile">File input</label>
                      <input type="file" id="exampleInputFile">
```

**Comment by ivantcholakov** [comment]
About  3 (a nice styled file input): I use this: http://www.jasny.net/bootstrap/javascript/#fileinput

**Comment by almasaeed2010** [comment]
Hello @RoyTerrazas 

AdminLTE is based on Bootstrap 3. ```span1``` is from Bootstrap 2. That's why it isn't working unless I misunderstood your question.

The mailbox page provides an example for the file input. Here is the code to create AdminLTE file input:
```html
<div class="form-group">
  <div class="btn btn-default btn-file">
    <i class="fa fa-paperclip"></i> Attachment
    <input type="file" name="attachment">
  </div>
  <p class="help-block">Max. 32MB</p>
</div>
```

In this example we used the class ```btn-file``` for the browse button.
