### ISSUE TITLE
Bootstrap in AdminLTE 3.0

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#778]
I am having a problem with loading Bootstrap using Bower in AdminLTE 3.0. The way I wanted to do it was to include BS with AdminLTE in one CSS file. To do that, I imported bootstrap.scss in AdminLTE.scss, which I realized then is problematic. When someone installs AdminLTE using Bower, they get AdminLTE and Bootstrap in different folders in their bower_components folder. This breaks the import in AdminLTE.scss.
```scss
// AdminLTE 3.0 SCSS
@import "../../bower_components/bootstrap/build/scss/bootstrap";
@import "custom_bootstrap_variables";

// rest of imports ...
```

While in development, the path to BS is ```../../bower_components/bootstrap/build/scss/bootstrap```. When installed via Bower, the path to BS changes to ```../../bootstrap/build/scss/bootstrap```. Thus, compiling AdminLTE.scss won't work.

The solution I attempted to implement was to use a bs_path variable so it can be easily adjusted. However, SASS doesn't support variable interpolation within an import statement. Therefore, this solution won't work.

Another solution is to revert back to manually downloading BS, but this takes away automatically updating bootstrap. We'd like to avoid this solution. We should also keep in mind that we need to support users who don't want to use bower or use different package managers.

What other solutions can you guys think of? Any ideas?

Thanks!

**Comment by recca0120** [comment]
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#load_paths-option

**Comment by recca0120** [comment]
eample here
https://gist.github.com/neekey/4480251

**Comment by almasaeed2010** [comment]
Thanks @recca0120 this is interesting. We might be able to use that with Grunt.

I'd still like to explore other possibilities.

**Comment by kohenkatz** [comment]
Yes, you can use @recca0120's suggestion with Grunt by including `loadPath` in the `options` object for sass in the `Gruntfile`.

Another way might be to have a Grunt (or Gulp, or shell) task that copies all of the contents of the `bower_components` directory up one level to the project root.  That way, the paths remain the same.  The one disadvantage of doing it this way is that the project root becomes polluted with lots of extra files which all have to be `gitignore`d.

A third option, which I think is the most elegant, though it is also the most complex to set up, is to have a `build` task of some kind that copies both the source AdminLTE files and the contents of the `bower_components` directory into another directory, which I'll call `build` and then runs SASS on the stuff in there instead of the stuff in the project root.

A variation on the third option would be that instead of the task copying everything into another directory, it would just copy all of the AdminLTE scripts into `bower_components/AdminLTE` and then run SASS in there.

Thoughts?

**Comment by kohenkatz** [comment]
@almasaeed2010 I have been looking around, and I found other projects that use @recca0120's suggestion. For example, see https://github.com/FezVrasta/bootstrap-material-design#bower
