### ISSUE TITLE
Using template with cms system. Template breaks ajax calls.

### ISSUE THREAD

**Issue by andyhughes73** [almasaeed2010/AdminLTE#820]
Hi,

I am using the template with a cms built on php called (phpvms). I have just noticed that when applying the template, the ajax calls from buttons etc stop working.

There are various buttons on the cms which makes calls using ajax to a database. Before installing the template, these worked fine and now they no longer function. Would you know why this might be? Could it be a version issue with JQuery or something?

**Comment by condor-bird** [comment]
Hello! Look at the console browser, whether there is an errors? If there is an errors, which ones.

**Comment by andyhughes73** [comment]
Ok I'm doing that in chrome, assuming that's ok. There are 5 errors, which I'll try to list below:

Uncaught ReferenceError: $ is not defined(anonymous function) @ viewpending:222

viewpending:464 Uncaught ReferenceError: $ is not defined(anonymous function) @ viewpending:464

jqModal.js:68 Uncaught TypeError: Cannot read property 'msie' of undefined(anonymous function) @ jqModal.js:68(anonymous function) @ jqModal.js:81

jQuery-2.1.4.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

morris.min.js:6 Uncaught Error: Graph container element not found
d @ morris.min.js:6
c @ morris.min.js:6
d @ morris.min.js:6
(anonymous function) @ viewpending:544

phpvmsadmin.js:214 Uncaught TypeError: $(...).live is not a function
reloadGroups @ phpvmsadmin.js:214
initListeners @ phpvmsadmin.js:28
(anonymous function) @ phpvmsadmin.js:22
j @ jQuery-2.1.4.min.js:2
k.fireWith @ jQuery-2.1.4.min.js:2
n.extend.ready @ jQuery-2.1.4.min.js:2
I @ jQuery-2.1.4.min.js:2
plugins.js:5005 Error: SEOquake disabled(…)
util.js:30 Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages

That's everything that's showing. I don't know JS or PHP that well but it looks to me like something is causing the ajax functions to execute, but I don't know what.

**Comment by rafael-renan-pacheco** [comment]
Is jQuery your first script being loaded?

**Comment by condor-bird** [comment]
For starters, check whether the path to the file jquery. Jquery library should be connected first, and only then the rest of the scripts.

**Comment by andyhughes73** [comment]
JQuery is my first script being loaded.

**Comment by condor-bird** [comment]
Jquery file path is correct? Properly set the path to the folder?
In template used AdminLTE - jQuery 2.1.4. What version you had before? If you were too old version, your scripts can not run.

``jqModal.js:68 Uncaught TypeError: Cannot read property 'msie' of undefined(anonymous function)``

http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed

``morris.min.js:6 Uncaught Error: Graph container element not found``

https://github.com/morrisjs/morris.js/issues/137


``
phpvmsadmin.js:214 Uncaught TypeError: $(...).live is not a function
``

Starting with version jQuery 1.7 method is <b>deprecated</b> ``live()``.
instead of ``.live ()``use the ``.on ()``
http://api.jquery.com/on/

So I assume that you have previously used into cms very old library jquery.

**Comment by andyhughes73** [comment]
It is indeed the case that the system cms I'm using, uses an older JQuery (1.4.2 & 1.8.0). I'm not clued up with javascript coding at all. Is there a way to run both jQuery libraries using something like modernizr or no conflict? The cms system I'm using is not really in development anymore and I think it would take a lot to convert all of the jquery and ajax to latest version.

**Comment by condor-bird** [comment]
Too bad that cms is no longer supported. Подумайте о передаче участка на другой CMS. Otherwise, if the project is a serious and large, in the future will encounter compatibility issues with PHP. Old scripts should be updated to the new version.
Modernizr - use detection methods.

Learn ``jQuery.noConflict():`` https://api.jquery.com/jquery.noconflict/
jQuery Core 1.9 Upgrade Guide: 
http://jquery.com/upgrade-guide/1.9/
Avoiding Conflicts with Other Libraries: 
http://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/

Use plug-in migration: https://github.com/jquery/jquery-migrate

**Comment by andyhughes73** [comment]
I have installed the Migrate file which has brought some functionality back. When I try to use Modernizr, it breaks everything and I just end up with a white blank page.

I get what you say about updating the old scripts. Unfortunately I wouldn't have the first clue how to update them as I'm not really a coder as such, just happy to try things.

I have also tried using the jQuery no conflict but it didn't seem to make any difference at all. Not sure quite where I was supposed to include the script so I put it in the head just before the </head> tag.

Just out of interest, below is the code which should trigger opening a box with some content in it. Is the code used to open the box ajax? i.e. the onclick bit, or is that plain php?

<button class="{button:{icons:{primary:'ui-icon-arrowthick-1-s'}}}"
		href="#" onclick="$('#details_dialog_<?php echo $pirep->pirepid;?>').toggle()">Details</button>

Thanks for your help, I do appreciate it very much.

**Comment by condor-bird** [comment]
``jQuery.noConflict()`` - allows you to work with several libraries jquery, or plug-ins that conflict with each other. Examples are listed above. Migrate should solve most of the problems.
``.toggle() `` -  Alternately performs one of several specified actions. Example, show or hide any block of text
When you click on the link works: ``$('#details_dialog_pirepid;').toggle()``

I do not quite understand your last question, about the code. Specify it differently.

I saw that there is a php: ``href="#" onclick="$('#details_dialog_pirepid;?>').toggle()">Details`` i.e. brace.

**Comment by andyhughes73** [comment]
I guess what I mean, relates to my lack of knowledge of ajax, jQuery etc. The code I pasted, is inside a button element. So when the button is pressed, a drop down box appears with the content populated from the link inside the button code (the code I pasted). What I don't know is; is the code above plain php or would it be classed as ajax/jQuery.

**Comment by condor-bird** [comment]
I'm sorry, maybe I again do not understand what you wrote. My bad English :D
On the provided code I see "click" event. When you click the link, the event is triggered and the function works: ``$('#details_dialog_pirepid;').toggle()``
Code is small, so I can only guess what is happening there. data is output by the ID `#details_dialog_pirepid``
