### ISSUE TITLE
Notification Popup - keep open

### ISSUE THREAD

**Issue by sajeelmuhammed** [almasaeed2010/AdminLTE#893]
In my I added a link button called "Mark all as read" (same as that of facebook). But when I click on the button, the popup disappears. I need to know how can I keep the notification popup as it is even when I click anywhere inside the popup. I want it to disappear only if I click anywhere outside the popup arena.

**Comment by YasserHassan** [comment]
Use `preventDefault()` with the appropriate element. Check this example http://www.w3schools.com/jquery/event_preventdefault.asp

**Comment by sajeelmuhammed** [comment]
@YasserHassan, I tried that method.
```javascript
$('.dropdown-menu').click(function(event){
    event.preventDefault();
});
```
But still its closing.

**Comment by YasserHassan** [comment]
I can't tell without seeing the context. For example, maybe the event handler was not attached correctly. You better try adding an alert or console log before `preventDefault()` and make sure they work right because it might not be a `preventDefault()` error after all. I recommend proceeding with this issue on Stack Overflow as it is not specific to AdminLTE as it is a generic web development issue.

**Comment by sajeelmuhammed** [comment]
@YasserHassan the click event is working fine. I tried console.log(). Is there any other work around?

**Comment by ikhsan017** [comment]
maybe you could try the ```e.stopPropagation()```?

**Comment by sajeelmuhammed** [comment]
Yes thats working. Thanks @ikhsan017
