### ISSUE TITLE
Using the AdminLTE theme

### ISSUE THREAD

**Issue by malutanpetronel** [almasaeed2010/AdminLTE#936]
It seems was not created in mind with something which shoudl immediately work !
I was changed my 
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}
to
{% extends 'AvanzuAdminThemeBundle:layout:base-layout.html.twig' %}
and I did the other config.yml suggested settings, but when I opened /admin/dashboard I was noticing that no links to my modules or no nav at the top which in the current version works !

Probably I did not understood the hole process of setting this theme ?

**Comment by YasserHassan** [comment]
AdminLTE is a client-side HTML template. Using it with a specific server-side language or framework is beyond the scope of the project. It could be used as a base project to create derivatives targeting other applications and there are already a couple of them available that you might be able use. Otherwise, you'll need to apply it to your project yourself.
