### ISSUE TITLE
$.AdminLTE.tree(".sidebar") - need to re-add this once dynamic Aurelia router is generated

### ISSUE THREAD

**Issue by LazerFX** [almasaeed2010/AdminLTE#963]
I'm working on an Aurelia templated-application, using AdminLTE to skin.  It's working really good, however the sidebar is not triggering properly.  Basically, the router (generating the sidebar) is A) in a template, and B) data-bound.  Because of this, the AdminLTE.tree($(".sidebar")) which appears to be called during the AdminLTE initialisation calls too early.  So, I re-called it after the router initialised.  However, if I then re-work the router and change the data-bindings, adding a new drop-down menu, only the already existing menu will still animate the tree; the other parts will not.  If I re-call AdminLTE.tree($(".sidebar")), the existing tree will open, and then promptly close; while the new one will open as expected.

What's the best way to handle a dynamically generated menu, re-built while the page is running?  Bearing in mind that the majority of the re-generation is done by the Aurelia templating and binding, so I've limited ability to plug in and amend that...

If I can provide any examples, please let me know the best place to put these - I think I can provide a minimum-case, if there's an online aurelia pastebin or similar....

**Comment by almasaeed2010** [comment]
Usually recalling AdminLTE.tree($('sidebar')) fixes this issue. However, it appears that in your case calling it multiple times causes a problem.

It would be ideal if you provide a testcase for us to experiment on.

Thanks!

**Comment by almasaeed2010** [comment]
We merged #904 which might have fixed your issue. Could you try downloading the master branch and trying again?

**Comment by LazerFX** [comment]
That's worked, thank you very much :)

**Comment by seichenberg** [comment]
Hi LazerFX - Is there any chance you share a seed project with AdminLTE or is there a way I can purchase a seed project using the AdminLTE ?

**Comment by seichenberg** [comment]
This would be for an Aurelia project.

**Comment by LazerFX** [comment]
@seichenberg I've actually since left the company that I was working on this project with, so I don't have the full details available to me, however the merge #904 did resolve this...  AdminLTE (at base) is an openly-available project, and we'd based everything on the Aurelia Skeleton project.  Both have significantly changed recently however, so the issue may not even be reproducible...  Sorry I can't provide any more information easily...

**Comment by seichenberg** [comment]
Thank you Peter for your response.

I wish AdminLTE had a template for Aurelia.  This is what I'm looking for because I don't have the skills to implement it just yet.

Do you know someone I can hire to do this?  Are the developer who initially integrated AdminLTE into Aurelia?

Thanks Peter!

Steven Eichenberg
561.596.8642
On 7/7/2016 8:54:27 AM, Peter Street <notifications@github.com> wrote:
@seichenberg [https://github.com/seichenberg] I've actually since left the company that I was working on this project with, so I don't have the full details available to me, however the merge #904 [https://github.com/almasaeed2010/AdminLTE/pull/904] did resolve this... AdminLTE (at base) is an openly-available project, and we'd based everything on the Aurelia Skeleton project. Both have significantly changed recently however, so the issue may not even be reproducible... Sorry I can't provide any more information easily...

**Comment by LazerFX** [comment]
@seichenberg I did actually do the integration with Aurelia, and it's relatively simple overall... I don't have any guides or anything on how to do this, and as I mentioned, Aurelia has now gone to release, and AdminLTE has changed somewhat.  I'd be happy to assist by e-mail if you want to send me a message through GitHub, though it'll have to take second priority to my day job, of course...

**Comment by seichenberg** [comment]
That is good to know.  How long do you think it would take and how much would it cost me?

Did you like Aurelia?  Would you use it again?

Steven Eichenberg
561.596.8642
On 7/7/2016 9:16:50 AM, Peter Street <notifications@github.com> wrote:
@seichenberg [https://github.com/seichenberg] I did actually do the integration with Aurelia, and it's relatively simple overall... I don't have any guides or anything on how to do this, and as I mentioned, Aurelia has now gone to release, and AdminLTE has changed somewhat. I'd be happy to assist by e-mail if you want to send me a message through GitHub, though it'll have to take second priority to my day job, of course...

**Comment by LazerFX** [comment]
I'll be honest, I'm not going to write it for you, but I will happily assist with any questions you've got, in the spirit of the help I had... I'm sure many others in the Aureila channel will likely do so as well - I got a lot of help on the [Aurelia Gitter](https://gitter.im/aurelia/Discuss).  As to if Aurelia is good - yes, very good, especially for an old WPF developer like myself, because it uses a lot of the same concepts for binding, navigation, updates, command iteration and such.

**Comment by seichenberg** [comment]
Hi Peter,

First of all, thanks for taking the time to respond to my questions.  I'm going to try and get it to work using typescript so we'll see what happens.  I might take you up when I run into a jam.

Regards,

Steven Eichenberg

Steven Eichenberg
561.596.8642
On 7/7/2016 9:28:48 AM, Peter Street <notifications@github.com> wrote:
I'll be honest, I'm not going to write it for you, but I will happily assist with any questions you've got, in the spirit of the help I had... I'm sure many others in the Aureila channel will likely do so as well - I got a lot of help on the Aurelia Gitter [https://gitter.im/aurelia/Discuss]. As to if Aurelia is good - yes, very good, especially for an old WPF developer like myself, because it uses a lot of the same concepts for binding, navigation, updates, command iteration and such.
