### ISSUE TITLE
TypeError: Cannot call method 'onCreated' of undefined

### ISSUE THREAD

**Issue by kalubunda** [almasaeed2010/AdminLTE#971]

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
