### ISSUE TITLE
boxed layout

### ISSUE THREAD

**Issue by iyurtsever** [almasaeed2010/AdminLTE#973]
Hello,

How can we set this template to work always boxed layout? I have some page designs which opens sometimes boxed, but sometimes fixed.
Regards

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
