### ISSUE TITLE
can i use for commercial purpose

### ISSUE THREAD

**Issue by ChiragDhangar** [almasaeed2010/AdminLTE#977]
i want to use it for my comapny website

**Comment by XzAeRo** [comment]
- You **CAN**:
  - Re-use the code freely for your own use.
  - Re-use the code freely for non-commercial AND commercial re-distribution, whether in source or binary form.
- You **CANNOT**:
  - Claim authorship of the software.
  - You cannot attack the original author for using or publishing his original version.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
