### ISSUE TITLE
Top Navigation Layout

### ISSUE THREAD

**Issue by gitricardosoares** [almasaeed2010/AdminLTE#978]
So i have encountered an issue i think, so if we have a long navbar items, we have to go on getbootstrap website if we go to customize and change the @grid-float-breakpoint from @screen-sm-min to @screen-md-min for example, and change the bootstrap files on AdminLTE folder the bars and the rest of the content on the right do not stay "organized" like the default navbar, there is another away to change the width of the navbar to collapse on AdminLTE? or it's really an issue?

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
