### ISSUE TITLE
Print preview error with showing sidebar

### ISSUE THREAD

**Issue by silebis** [almasaeed2010/AdminLTE#980]
Chrome 49 and Internet Explorer 10 is showing in the latest version of AdminLTE bug with sidebar in print preview. 

![image](https://cloud.githubusercontent.com/assets/1327438/13952553/4896bd90-f037-11e5-975e-c2eab42068bf.png)

**Comment by matbeard** [comment]
I've also got this issue. It doesn't appear when using the 'Emulate print media' option in Chrome dev tools... just in the print preview (and printed page, obviously). I've tried all sorts of overrides in the print media CSS, but I can't get rid of the left margin/padding.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.

**Comment by austenc** [comment]
@silebis did you find a solution to this?

**Comment by sar009** [comment]
@almasaeed2010 where you able to find a solution for this
