### ISSUE TITLE
Stop Carousel Autoplay

### ISSUE THREAD

**Issue by hansaliyad1** [almasaeed2010/AdminLTE#981]
Hey there!

I like Admin LTE so much. I am trying to use it for my work space. I am using Carousel in my project and I was just wondering how can I stop it from auto-playing the slides?

Thank you so much in advance for help

**Comment by XzAeRo** [comment]
Just add `data-interval="false"` to the Carousel container.
[Source](http://getbootstrap.com/javascript/#carousel-options)

**Comment by mr-yound** [comment]
sdfdsdsfdfs

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
