### ISSUE TITLE
Form fields side by side

### ISSUE THREAD

**Issue by FMaynard** [almasaeed2010/AdminLTE#986]
How can I arrange form fileds so it looks like the atached example image?

![screen](https://cloud.githubusercontent.com/assets/8160414/14024705/45cf87ac-f1c9-11e5-8e7e-2019dccf869e.jpg)

**Comment by Tjoosten** [comment]
i think you should look to the bootstrap documentation

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
