### ISSUE TITLE
Control Sidebar not opening on Single Page Application

### ISSUE THREAD

**Issue by aindong** [almasaeed2010/AdminLTE#987]
Hello, 
I've been trying to create a spa app using react, and used admin lte as my main template. When I'm about to use the Control Sidebar, it shows some weirdness in it. On the first load of the app, it will work properly, but then when I switch to other page using react-router, and goes back into the page where control sidebar is implemented, it's not working. Please help, thanks in advance

**Comment by timurey** [comment]
I don't know, how react works. In ember.js you need to run ```$.AdminLTE.controlSidebar.activate();``` after adding control-sidebar in page.

**Comment by hiepnm** [comment]
I have met the same problem when using AdminLTE with ui-router in AngularJS.

**Comment by marrullas** [comment]
Use this
[example](http://stackoverflow.com/questions/35556569/adminlte-and-angularjs-content-wrapper-wrong-min-height)

in the code you put something like


```
in header:

<li (click) = "mostratAside()">
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>`

In component


mostratAside(){
        getAdminLTE().controlSidebar.activate('click');
        console.log('click');
        
    }
```
I hope you understand me

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.

**Comment by DarioN1** [comment]
I'm having the same problem working with an Angular4 application...
