### ISSUE TITLE
Data Table where a click in a row shows extra data about selected row

### ISSUE THREAD

**Issue by Oz-rod** [almasaeed2010/AdminLTE#988]
Hello Everyone,

I need to show in a Data Table where the data are getting to through of PHP and MariaDB. After, when I click in any row, it shows extra data about the row selected and two buttons in the section just to right of the data table.

Is it possible?

Regards friends

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
