### ISSUE TITLE
Drop down user menu isnt working in laravel blade

### ISSUE THREAD

**Issue by Amanlte** [almasaeed2010/AdminLTE#990]
i have the heder section of adminlte in the mani layout and i have ajax call for content loading but after the ajax call the dropdown user menu needs reload to work/toggle. I am trying to have something like single page app ..just loading only the content section using ajax

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
