### ISSUE TITLE
moment is not define

### ISSUE THREAD

**Issue by ariesastra** [almasaeed2010/AdminLTE#993]
i have a problem like this in my firebug

![1](https://cloud.githubusercontent.com/assets/18027921/14097486/9e1ebd8a-f59b-11e5-8324-9211e023e9f6.JPG)

how to fix it ? i'm using **Laravel** for this template

and my chart didn't show
![1](https://cloud.githubusercontent.com/assets/18027921/14097602/0a492a4e-f59d-11e5-935d-a58f7c94aec7.JPG)

Thankyou for everyone :)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
