### ISSUE TITLE
https://github.com/almasaeed2010/AdminLTE/issues/685

### ISSUE THREAD

**Issue by rishabhack** [almasaeed2010/AdminLTE#994]
TypeError: $(...).modal is not a function
very serious issue unable to use model via ajaxmodelpopup and also via jquery above method.
waiting for solution.
big issue in adminlte.
same issue which was closed but not resolved.
https://github.com/almasaeed2010/AdminLTE/issues/685

on jsfiddle working and also working in other project but not working in adminlte
order of jquery file and bootstrap checked.

**Comment by madalinignisca** [comment]
.modal is not available if the bootstrap modal component has not been initialised.
this has nothing to do with AdminLTE, it is on how you set the order for your javascript to execute.

As you don't provide a proper description of your issue, my bet is that you called `$(somemodal).modal({options})` before [Bootstrap's modal](https://github.com/twbs/bootstrap/blob/master/js/modal.js) has loaded.

You can check that using Chrome's inspector as it has the necessary tool to see how JS is loaded and executed step by step visually.

I had similar issues a while ago 👍  but I took a bit of time to really understand JavaScript loading and execution.

I suggest closing the issue as it's not AdminLTE related.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
