### ISSUE TITLE
Strange search input when autofocus included

### ISSUE THREAD

**Issue by nicozimmermann94** [almasaeed2010/AdminLTE#995]
Hello. I noticed a very strange bug: as soon as somewhere in the markup an input with autofocus is included, the standard search field in the top left corner does some strange animation while refreshing the page. It only happens on firefox as far as I tested. Here is the behaviour:

![with](https://cloud.githubusercontent.com/assets/9193934/14106751/b39dbf40-f5b3-11e5-8b2b-ea5cb6b58cce.gif)

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.

**Comment by nicozimmermann94** [comment]
Hey, maybe you can reopen this issue?

**Comment by almasaeed2010** [comment]
Fixed in master. Next release to have this patch will be 2.3.4.

Thanks!
