### ISSUE TITLE
User Name popup on right most upper corner not working with datatable 1.10+

### ISSUE THREAD

**Issue by vjkr14** [almasaeed2010/AdminLTE#996]
When I am using datatable 1.10 *.min.js user details pull details under top nav does not works.

**Comment by almasaeed2010** [comment]
Due to some neglect in my part, many issues weren't addressed for some time. Some of these issues are no longer relevant since a solution might have been found. Therefore, we decided to close all issues that are over a month old. However, if the issue still persists and you'd like help, then by all means repost your issue and we will consider it again. In the mean time, we will close this post.

Thanks for your understanding and we apologize for any inconvenience <3.
